// Writes steam/achievements.json: every achievement in js/ach.js (and 4.0 Deeds, when a file passed on the command
// line defines G.DEEDS = [{id, name, desc}]) with its Steam API name, display name and description, for the
// Steamworks partner site (App Admin → Stats & Achievements) and for the game (tools/build.js --target steam inlines
// the id → API name map). API names: 'ACH_' + the id in capitals, A-Z 0-9 and _ only; never rename one once
// published (Steam keys unlocks by API name).
// Usage: node steam/achievements.js [more js files that define G.DEEDS ...]
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.join(__dirname, '..');
const G = { on() {}, emit() {}, t: k => k, L: s => s || '' };
const ctx = vm.createContext({ globalThis: {}, console, Math, Date, JSON });
ctx.globalThis.G = G;
for (const f of ['js/ach.js'].concat(process.argv.slice(2))) {
  vm.runInContext(fs.readFileSync(path.join(root, f), 'utf8'), ctx, { filename: f });
}
const apiName = (pre, id) => (pre + String(id).toUpperCase().replace(/[^A-Z0-9_]/g, '_')).slice(0, 64);
const rows = [];
const seen = new Set();
const add = (kind, a, pre) => {
  if (!a || !a.id || seen.has(a.id)) return;
  seen.add(a.id);
  rows.push({ id: a.id, api: apiName(pre, a.id), kind, name: String(a.name || a.id), desc: String(a.desc || ''), hidden: !!a.hidden });
};
(G.ACH || []).forEach(a => add('ach', a, 'ACH_'));
(G.DEEDS || []).forEach(d => add('deed', d, 'DEED_'));
const apis = new Set(rows.map(r => r.api));
if (apis.size !== rows.length) throw new Error('two achievements map to one Steam API name');
const out = {
  note: 'Generated by node steam/achievements.js from js/ach.js (+ G.DEEDS). Steam API names must never change once published. Each row needs an achieved and an unachieved icon at the size the partner site asks for (see steam/README.md).',
  count: rows.length,
  achievements: rows,
};
fs.writeFileSync(path.join(__dirname, 'achievements.json'), JSON.stringify(out, null, 2) + '\n');
console.log('steam/achievements.json', rows.length, 'achievements');
