// Generated by tools/build.js — do not edit. Game logic shared with the client.
/* js/util.js */
// BTTN — shared helpers. Every file attaches to the global G namespace so the
// game runs from file://, as a single inlined page, and inside a Node sim.
(function (G) {
  'use strict';

  const SUFFIXES = ['', 'K', 'M', 'B', 'T', 'Qa', 'Qi', 'Sx', 'Sp', 'Oc', 'No', 'Dc',
    'UDc', 'DDc', 'TDc', 'QaDc', 'QiDc', 'SxDc', 'SpDc', 'OcDc', 'NoDc', 'Vg'];

  // Compact number: 999, 1.23K, 45.6M, 7.89e75
  function fmt(n, small) {
    if (n === undefined || n === null || Number.isNaN(n)) return '0';
    if (!Number.isFinite(n)) return '∞';
    const neg = n < 0; if (neg) n = -n;
    let s;
    if (n < 1000) {
      if (small && n < 10 && n % 1 !== 0) s = (Math.floor(n * 10) / 10).toString();
      else if (small && n < 100 && n % 1 !== 0) s = (Math.floor(n * 10) / 10).toFixed(1);
      else s = Math.floor(n).toString();
    } else {
      const e = Math.floor(Math.log10(n) / 3);
      if (e < SUFFIXES.length) {
        const v = n / Math.pow(1000, e);
        const d = v < 10 ? 2 : v < 100 ? 1 : 0;
        s = (Math.floor(v * Math.pow(10, d)) / Math.pow(10, d)).toFixed(d) + SUFFIXES[e];
      } else {
        const ex = Math.floor(Math.log10(n));
        s = (n / Math.pow(10, ex)).toFixed(2) + 'e' + ex;
      }
    }
    return (neg ? '-' : '') + s;
  }

  function fmtPct(x) { // 0.25 -> +25%
    const v = x * 100;
    return (v >= 0 ? '+' : '') + (Math.abs(v) < 10 && v % 1 ? v.toFixed(1) : Math.round(v)) + '%';
  }

  function fmtTime(sec) {
    sec = Math.max(0, Math.floor(sec));
    const d = Math.floor(sec / 86400), h = Math.floor(sec % 86400 / 3600),
      m = Math.floor(sec % 3600 / 60), s = sec % 60;
    if (d) return d + 'd ' + h + 'h';
    if (h) return h + 'h ' + m + 'm';
    if (m) return m + 'm ' + s + 's';
    return s + 's';
  }

  const clamp = (v, a, b) => v < a ? a : v > b ? b : v;
  const lerp = (a, b, t) => a + (b - a) * t;
  // All game randomness goes through G.rng so a run can be replayed from a seed
  // (G.useSeed) — the base for a cheat-resistant ladder. Visual effects may
  // keep using Math.random.
  G.rng = Math.random;
  const rnd = () => G.rng();
  const rand = (a = 0, b = 1) => a + rnd() * (b - a);
  const randInt = (a, b) => Math.floor(a + rnd() * (b - a + 1));
  const pick = arr => arr[Math.floor(rnd() * arr.length)];
  const chance = p => rnd() < p;

  function weighted(weights) { // returns index
    let total = 0;
    for (let i = 0; i < weights.length; i++) total += weights[i];
    let r = rnd() * total;
    for (let i = 0; i < weights.length; i++) { r -= weights[i]; if (r < 0) return i; }
    return weights.length - 1;
  }

  // Deterministic RNG for level decoration so a biome always looks the same.
  function seeded(seed) {
    let a = seed >>> 0;
    return function () {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      let t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }

  G.useSeed = seed => { G.rng = seed == null ? Math.random : seeded(seed); };

  function todayKey(d) {
    d = d || new Date();
    return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0');
  }

  // Sum of geometric series cost: buying `n` levels starting from level L.
  function geoCost(base, growth, L, n) {
    if (n <= 0) return 0;
    if (growth === 1) return base * n;
    return base * Math.pow(growth, L) * (Math.pow(growth, n) - 1) / (growth - 1);
  }
  // How many levels are affordable with `money`.
  function geoMax(base, growth, L, money) {
    const first = base * Math.pow(growth, L);
    if (money < first) return 0;
    return Math.floor(Math.log(money * (growth - 1) / first + 1) / Math.log(growth));
  }

  const hexToRgb = h => {
    h = h.replace('#', '');
    if (h.length === 3) h = h.split('').map(c => c + c).join('');
    const n = parseInt(h, 16);
    return [n >> 16 & 255, n >> 8 & 255, n & 255];
  };
  const rgbToHex = (r, g, b) => '#' + [r, g, b].map(v => clamp(Math.round(v), 0, 255).toString(16).padStart(2, '0')).join('');
  function shade(hex, amt) { // amt -1..1
    const [r, g, b] = hexToRgb(hex);
    if (amt >= 0) return rgbToHex(r + (255 - r) * amt, g + (255 - g) * amt, b + (255 - b) * amt);
    return rgbToHex(r * (1 + amt), g * (1 + amt), b * (1 + amt));
  }

  // Tiny event bus: logic emits, stage/ui/audio listen.
  const listeners = {};
  function on(ev, fn) { (listeners[ev] = listeners[ev] || []).push(fn); }
  function emit(ev, a, b, c) {
    const l = listeners[ev]; if (!l) return;
    for (let i = 0; i < l.length; i++) l[i](a, b, c);
  }

  Object.assign(G, {
    fmt, fmtPct, fmtTime, clamp, lerp, rand, randInt, pick, chance, weighted, seeded,
    todayKey, geoCost, geoMax, hexToRgb, rgbToHex, shade, on, emit,
  });
})(globalThis.G = globalThis.G || {});

/* js/data.js */
// BTTN — all game content. Names are bilingual {ru, en}; descriptions use {0}
// placeholders filled from val(level). Effects are applied in G.recalc().
(function (G) {
  'use strict';

  // ---------- Rarities ----------
  // secs: item value measured in "seconds of income" so chests stay relevant all game.
  G.RARITIES = [
    { id: 'common',    name: { ru: 'Обычный',       en: 'Common' },    color: '#c7b299', dark: '#7a6650', secs: 0.4,    ess: 0.06, bonusMul: 1 },
    { id: 'uncommon',  name: { ru: 'Необычный',     en: 'Uncommon' },  color: '#63d85b', dark: '#2d7a28', secs: 1,    ess: 0.14, bonusMul: 1.5 },
    { id: 'rare',      name: { ru: 'Редкий',        en: 'Rare' },      color: '#4fa8ff', dark: '#1f5aa8', secs: 2.5,   ess: 0.35, bonusMul: 2 },
    { id: 'epic',      name: { ru: 'Эпический',     en: 'Epic' },      color: '#b36bff', dark: '#5f2aa8', secs: 6,   ess: 0.9,  bonusMul: 3 },
    { id: 'legendary', name: { ru: 'Легендарный',   en: 'Legendary' }, color: '#ffa033', dark: '#a8560f', secs: 16,  ess: 2.4,  bonusMul: 4 },
    { id: 'mythic',    name: { ru: 'Мифический',    en: 'Mythic' },    color: '#ff4f7e', dark: '#9e1f44', secs: 50,  ess: 6,    bonusMul: 6 },
    { id: 'divine',    name: { ru: 'Божественный',  en: 'Divine' },    color: '#ffffff', dark: '#9aa6c0', secs: 160, ess: 18,   bonusMul: 10 },
  ];
  // Base chest tier weights before luck.
  G.CHEST_WEIGHTS = [1000, 280, 80, 22, 6, 1.5, 0.3];
  G.STAR_THRESHOLDS = [1, 10, 100, 1000, 10000];

  // ---------- Collection bonus types (per star, before rarity multiplier) ----------
  G.BONUS = {
    click: { v: 0.02,  name: { ru: 'Сила клика', en: 'Click gold' },       pct: true },
    gps:   { v: 0.01,  name: { ru: 'Доход героев', en: 'Hero income' },     pct: true },
    gold:  { v: 0.01,  name: { ru: 'Всё золото', en: 'All gold' },          pct: true },
    crit:  { v: 0.001, name: { ru: 'Шанс крита', en: 'Crit chance' },       pct: true },
    critd: { v: 0.1,   name: { ru: 'Сила крита', en: 'Crit power' },        pct: false, x: true },
    luck:  { v: 0.005, name: { ru: 'Удача', en: 'Luck' },                   pct: true },
    ess:   { v: 0.015, name: { ru: 'Эссенция', en: 'Essence' },             pct: true },
    item:  { v: 0.02,  name: { ru: 'Цена предметов', en: 'Item value' },    pct: true },
    boss:  { v: 0.03,  name: { ru: 'Урон по боссам', en: 'Boss damage' },   pct: true },
    chest: { v: 0.015, name: { ru: 'Частота сундуков', en: 'Chest rate' },  pct: true },
    egg:   { v: 0.02,  name: { ru: 'Шанс яиц', en: 'Egg chance' },          pct: true },
    pet:   { v: 0.015, name: { ru: 'Сила питомцев', en: 'Pet power' },      pct: true },
    combo: { v: 2,     name: { ru: 'Макс. комбо', en: 'Max combo' },        pct: false },
  };

  // ---------- Items: 7 rarities x 6. w = drop weight inside the rarity, m = value multiplier ----------
  const W = [30, 25, 20, 13, 8, 4], M = [0.7, 0.85, 1.0, 1.25, 1.6, 2.2];
  const itemRows = [
    [ // common
      ['rusty_dagger', 'Ржавый кинжал', 'Rusty Dagger', 'click'],
      ['twig_staff', 'Посох-ветка', 'Twig Staff', 'ess'],
      ['short_bow', 'Короткий лук', 'Short Bow', 'crit'],
      ['leather_vest', 'Кожаная куртка', 'Leather Vest', 'gps'],
      ['copper_ring', 'Медное кольцо', 'Copper Ring', 'luck'],
      ['old_boot', 'Старый сапог', 'Old Boot', 'item'],
    ],
    [ // uncommon
      ['steel_sword', 'Стальной меч', 'Steel Sword', 'click'],
      ['oak_wand', 'Дубовая палочка', 'Oak Wand', 'ess'],
      ['hunter_bow', 'Охотничий лук', "Hunter's Bow", 'critd'],
      ['chainmail', 'Кольчуга', 'Chainmail', 'boss'],
      ['emerald_ring', 'Изумрудное кольцо', 'Emerald Ring', 'luck'],
      ['hp_potion', 'Зелье здоровья', 'Health Potion', 'gold'],
    ],
    [ // rare
      ['sapphire_blade', 'Сапфировый клинок', 'Sapphire Blade', 'click'],
      ['frost_staff', 'Ледяной посох', 'Frost Staff', 'ess'],
      ['crystal_dagger', 'Хрустальный кинжал', 'Crystal Dagger', 'crit'],
      ['knight_shield', 'Рыцарский щит', "Knight's Shield", 'boss'],
      ['mana_tome', 'Том маны', 'Mana Tome', 'pet'],
      ['sapphire_amulet', 'Сапфировый амулет', 'Sapphire Amulet', 'chest'],
    ],
    [ // epic
      ['shadow_katana', 'Теневая катана', 'Shadow Katana', 'critd'],
      ['necro_skull', 'Череп некроманта', 'Necro Skull', 'ess'],
      ['arcane_orb', 'Чародейская сфера', 'Arcane Orb', 'gps'],
      ['demon_helm', 'Шлем демона', 'Demon Helm', 'boss'],
      ['void_cloak', 'Плащ пустоты', 'Void Cloak', 'combo'],
      ['amethyst_tiara', 'Аметистовая тиара', 'Amethyst Tiara', 'egg'],
    ],
    [ // legendary
      ['dragon_sword', 'Меч дракона', 'Dragonfire Sword', 'click'],
      ['phoenix_bow', 'Лук феникса', 'Phoenix Bow', 'crit'],
      ['sun_staff', 'Солнечный посох', 'Sunstaff', 'gps'],
      ['golden_plate', 'Золотые латы', 'Golden Plate', 'gold'],
      ['titan_ring', 'Кольцо титана', 'Titan Ring', 'luck'],
      ['ancient_scroll', 'Древний свиток', 'Ancient Scroll', 'item'],
    ],
    [ // mythic
      ['blood_scythe', 'Кровавая коса', 'Blood Scythe', 'critd'],
      ['star_codex', 'Звёздный фолиант', 'Star Codex', 'ess'],
      ['chaos_wand', 'Жезл хаоса', 'Chaos Wand', 'chest'],
      ['moon_orb', 'Лунная сфера', 'Bloodmoon Orb', 'pet'],
      ['realm_heart', 'Сердце Королевства', 'Heart of the Realm', 'gold'],
      ['king_crown', 'Корона королей', 'Crown of Kings', 'boss'],
    ],
    [ // divine
      ['eternity_blade', 'Клинок вечности', 'Eternity Blade', 'click'],
      ['celestial_staff', 'Небесный посох', 'Celestial Staff', 'gps'],
      ['halo', 'Нимб', 'Halo', 'luck'],
      ['seraph_wing', 'Крыло серафима', 'Seraph Wing', 'egg'],
      ['cosmic_egg', 'Космическое яйцо', 'Cosmic Egg', 'pet'],
      ['golden_button', 'Золотая кнопка', 'The Golden Button', 'gold'],
    ],
  ];
  G.ITEMS = [];
  G.ITEMS_BY_RARITY = [];
  itemRows.forEach((row, r) => {
    G.ITEMS_BY_RARITY[r] = [];
    row.forEach((it, i) => {
      const item = { id: it[0], r, name: { ru: it[1], en: it[2] }, bonus: it[3], w: W[i], m: M[i], idx: G.ITEMS.length };
      G.ITEMS.push(item);
      G.ITEMS_BY_RARITY[r].push(item);
    });
  });
  G.ITEM_BY_ID = {};
  G.ITEMS.forEach(it => G.ITEM_BY_ID[it.id] = it);

  // ---------- Heroes (idle income) ----------
  G.HERO_MILESTONES = [10, 25, 50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 800, 900, 1000];
  G.HEROES = [
    { id: 'rogue',    name: { ru: 'Разбойник', en: 'Rogue' },       cost: 50,     gps: 0.2,    shot: '#9aa0a8' },
    { id: 'archer',   name: { ru: 'Лучник', en: 'Archer' },         cost: 400,    gps: 1.2,    shot: '#9be15d' },
    { id: 'wizard',   name: { ru: 'Маг', en: 'Wizard' },            cost: 4500,   gps: 8,      shot: '#5ab4ff' },
    { id: 'priest',   name: { ru: 'Жрица', en: 'Priestess' },       cost: 50000,  gps: 45,     shot: '#fff3a0' },
    { id: 'warrior',  name: { ru: 'Воин', en: 'Warrior' },          cost: 5.5e5,  gps: 260,    shot: '#ff7a4a' },
    { id: 'knight',   name: { ru: 'Рыцарь', en: 'Knight' },         cost: 6e6,  gps: 1400,   shot: '#cfd8e0' },
    { id: 'paladin',  name: { ru: 'Паладин', en: 'Paladin' },       cost: 8.5e7,  gps: 7800,   shot: '#ffd84a' },
    { id: 'necro',    name: { ru: 'Некромант', en: 'Necromancer' }, cost: 1.3e9,  gps: 44000,  shot: '#c06bff' },
    { id: 'mystic',   name: { ru: 'Мистик', en: 'Mystic' },         cost: 2e10,  gps: 2.6e5,  shot: '#ff6bd8' },
    { id: 'sorcerer', name: { ru: 'Чародей', en: 'Sorcerer' },      cost: 3e11, gps: 1.6e6,  shot: '#ff4040' },
    { id: 'ninja',    name: { ru: 'Ниндзя', en: 'Ninja' },          cost: 4e12,   gps: 1e7,    shot: '#ffffff' },
    { id: 'summoner', name: { ru: 'Призыватель', en: 'Summoner' },  cost: 5.5e13, gps: 6.5e7,  shot: '#6bffb0' },
  ];
  G.HERO_GROWTH = 1.15;
  G.FINGER_MILESTONES = [10, 25, 50, 75, 100, 125, 150, 200];

  // ---------- Shop upgrades (gold) ----------
  G.UPGRADES = [
    { id: 'finger', icon: 'ic_finger', base: 15, growth: 1.5, max: 0,
      name: { ru: 'Крепкий палец', en: 'Iron Finger' },
      desc: { ru: '+1 к силе клика. На 10, 25, 50, 75… ур. — клик ×2', en: '+1 click power. Levels 10, 25, 50, 75… double clicks' },
      fx: (L, D) => { D.clickAdd += L; D.clickMult *= Math.pow(2, G.FINGER_MILESTONES.filter(m => L >= m).length); } },
    { id: 'might', icon: 'ic_rune', base: 5000, growth: 30, max: 15,
      name: { ru: 'Руна силы', en: 'Rune of Might' },
      desc: { ru: 'Сила клика ×1.5 за уровень', en: 'Click gold ×1.5 per level' },
      fx: (L, D) => { D.clickMult *= Math.pow(1.5, L); } },
    { id: 'echo', icon: 'ic_echo', base: 100000.0, growth: 15, max: 10,
      name: { ru: 'Эхо-удар', en: 'Echo Strike' },
      desc: { ru: 'Клик даёт +1% дохода героев в сек. за уровень', en: 'Each click adds +1% of hero income per level' },
      fx: (L, D) => { D.clickGpsPct += 0.01 * L; } },
    { id: 'keen', icon: 'ic_eye', base: 200, growth: 2.5, max: 20,
      name: { ru: 'Зоркий глаз', en: 'Keen Eye' },
      desc: { ru: '+0.5% шанс критического клика', en: '+0.5% critical click chance' },
      fx: (L, D) => { D.crit += 0.005 * L; } },
    { id: 'deadly', icon: 'ic_skull', base: 1000, growth: 3.5, max: 15,
      name: { ru: 'Смертельный удар', en: 'Deadly Blow' },
      desc: { ru: 'Множитель крита +0.5', en: 'Crit multiplier +0.5' },
      fx: (L, D) => { D.critMult += 0.5 * L; } },
    { id: 'sense', icon: 'ic_nose', base: 100, growth: 2.4, max: 20,
      name: { ru: 'Чутьё кладоискателя', en: 'Treasure Sense' },
      desc: { ru: 'Сундуки появляются на 5% чаще', en: 'Chests appear 5% more often' },
      fx: (L, D) => { D.chestProg += 0.05 * L; } },
    { id: 'hall', icon: 'ic_hall', base: 300, growth: 3.5, max: 10,
      name: { ru: 'Просторный зал', en: 'Spacious Hall' },
      desc: { ru: '+1 место для сундуков', en: '+1 chest slot' },
      fx: (L, D) => { D.slots += L; } },
    { id: 'golem', icon: 'ic_key', base: 2500, growth: 3, max: 20,
      name: { ru: 'Ключ-голем', en: 'Key Golem' },
      desc: { ru: 'Сам открывает сундуки. Каждый ур. на 12% быстрее', en: 'Opens chests for you. Each level is 12% faster' },
      fx: (L, D) => { if (L > 0) D.autoOpen = 8 * Math.pow(0.88, L - 1); } },
    { id: 'clover', icon: 'ic_clover', base: 1000, growth: 2.8, max: 20,
      name: { ru: 'Четырёхлистник', en: 'Four-Leaf Clover' },
      desc: { ru: '+3% удачи: сундуки лучше', en: '+3% luck: better chests' },
      fx: (L, D) => { D.luck += 0.03 * L; } },
    { id: 'appraiser', icon: 'ic_scale', base: 500, growth: 2.8, max: 20,
      name: { ru: 'Оценщик', en: 'Appraiser' },
      desc: { ru: 'Предметы стоят на 5% дороже', en: 'Items are worth 5% more' },
      fx: (L, D) => { D.itemMult *= 1 + 0.05 * L; } },
    { id: 'rhythm', icon: 'ic_note', base: 1000, growth: 4, max: 10,
      name: { ru: 'Ритм', en: 'Rhythm' },
      desc: { ru: 'Максимальное комбо +25', en: 'Max combo +25' },
      fx: (L, D) => { D.comboCap += 25 * L; } },
    { id: 'clockwork', icon: 'ic_gear', base: 10000, growth: 2.8, max: 20,
      name: { ru: 'Заводная рука', en: 'Clockwork Hand' },
      desc: { ru: '+0.5 автоклика в секунду', en: '+0.5 auto clicks per second' },
      fx: (L, D) => { D.autoCps += 0.5 * L; } },
    { id: 'prince', icon: 'ic_crown', base: 1e17, growth: 1, max: 1, secret: 1e13,
      name: { ru: 'Корона Принца', en: "The Prince's Crown" },
      desc: { ru: 'Всё золото ×3. Кнопка коронована.', en: 'All gold ×3. The Button is crowned.' },
      fx: (L, D) => { if (L) D.goldMult *= 3; } },
  ];

  // ---------- Chest modifiers ----------
  G.MODIFIERS = [
    { id: 'golden',    color: '#ffd84a', name: { ru: 'Золотой', en: 'Golden' },          desc: { ru: 'Взрыв золота при открытии', en: 'Bursts with gold' } },
    { id: 'lightning', color: '#7fe9ff', name: { ru: 'Грозовой', en: 'Storm' },          desc: { ru: 'Молния открывает соседние сундуки', en: 'Lightning opens nearby chests' } },
    { id: 'ghost',     color: '#d8e6ff', name: { ru: 'Призрачный', en: 'Ghost' },        desc: { ru: 'Содержимое удваивается', en: 'Loot is duplicated' } },
    { id: 'chromatic', color: '#ff7ae6', name: { ru: 'Хроматический', en: 'Chromatic' }, desc: { ru: 'Лучший из 3 бросков редкости', en: 'Best of 3 rarity rolls' } },
    { id: 'frozen',    color: '#9fd8ff', name: { ru: 'Ледяной', en: 'Frozen' },          desc: { ru: 'Разбей лёд (8 кликов) — 3 предмета', en: 'Crack the ice (8 clicks) for 3 items' } },
    { id: 'blazing',   color: '#ff7a2e', name: { ru: 'Пылающий', en: 'Blazing' },        desc: { ru: 'Цена ×5, но сгорает за 6 сек', en: '×5 value, burns out in 6s' } },
    { id: 'mimic',     color: '#d94040', name: { ru: 'Мимик', en: 'Mimic' },             desc: { ru: 'Кусается! Победи — 5 предметов', en: 'It bites! Defeat it for 5 items' } },
    { id: 'void',      color: '#8a4dff', name: { ru: 'Бездонный', en: 'Void' },          desc: { ru: 'Эссенция ×10', en: '×10 essence' } },
  ];
  G.MOD_BY_ID = {}; G.MODIFIERS.forEach(m => G.MOD_BY_ID[m.id] = m);

  // ---------- Constellation (essence skill tree) ----------
  // x,y on a grid centred at 0,0. req: any one of these unlocks the node.
  const C = (id, x, y, br, req, max, cost, growth, name, desc, fx, val) => ({ id, x, y, br, req, max, cost, growth, name, desc, fx, val });
  G.NODES = [
    C('spark', 0, 0, 'core', [], 5, 1, 1.6, { ru: 'Искра', en: 'Spark' }, { ru: 'Всё золото +10%', en: 'All gold +10%' },
      (L, D) => { D.goldMult *= 1 + 0.1 * L; }),
    // Click arm (up)
    C('c_surge', 0, -1, 'click', ['spark'], 5, 2, 1.7, { ru: 'Прилив силы', en: 'Power Surge' }, { ru: 'Клик +20%', en: 'Click gold +20%' },
      (L, D) => { D.clickMult *= 1 + 0.2 * L; }),
    C('c_prec', -1, -2, 'click', ['c_surge'], 5, 4, 1.8, { ru: 'Точность', en: 'Precision' }, { ru: 'Шанс крита +1%', en: 'Crit chance +1%' },
      (L, D) => { D.crit += 0.01 * L; }),
    C('c_brut', 1, -2, 'click', ['c_surge'], 5, 4, 1.8, { ru: 'Жестокость', en: 'Brutality' }, { ru: 'Множитель крита +1', en: 'Crit multiplier +1' },
      (L, D) => { D.critMult += 1 * L; }),
    C('c_flow', 0, -3, 'click', ['c_prec', 'c_brut'], 3, 12, 2.2, { ru: 'Поток', en: 'Flow' }, { ru: 'Макс. комбо +40', en: 'Max combo +40' },
      (L, D) => { D.comboCap += 40 * L; }),
    C('c_echo', -1, -4, 'click', ['c_flow'], 5, 30, 2, { ru: 'Отголосок', en: 'Resonance' }, { ru: 'Клик +1% дохода героев', en: 'Clicks +1% of hero income' },
      (L, D) => { D.clickGpsPct += 0.01 * L; }),
    C('c_frenzy', 1, -4, 'click', ['c_flow'], 3, 25, 2, { ru: 'Упоение', en: 'Rapture' }, { ru: 'Бафы огоньков длятся на 25% дольше', en: 'Wisp buffs last 25% longer' },
      (L, D) => { D.buffDur += 0.25 * L; }),
    C('c_thunder', 0, -5, 'click', ['c_echo', 'c_frenzy'], 1, 200, 1, { ru: 'Громовая длань', en: 'Thunder Palm' }, { ru: 'Каждый 25-й клик — МЕГА-клик ×30', en: 'Every 25th click is a MEGA click ×30' },
      (L, D) => { D.mega = L > 0; }),
    // Idle arm (right)
    C('i_guild', 1, 0, 'idle', ['spark'], 5, 2, 1.7, { ru: 'Гильдия', en: 'Guild Hall' }, { ru: 'Доход героев +15%', en: 'Hero income +15%' },
      (L, D) => { D.gpsMult *= 1 + 0.15 * L; }),
    C('i_vet', 2, -1, 'idle', ['i_guild'], 3, 10, 2.5, { ru: 'Ветераны', en: 'Veterans' }, { ru: 'Герои +0.5% за каждые 10 героев', en: 'Heroes +0.5% per 10 heroes owned' },
      (L, D) => { D.vet += 0.005 * L; }),
    C('i_scout', 2, 1, 'idle', ['i_guild'], 5, 8, 2, { ru: 'Разведчики', en: 'Scouts' }, { ru: 'Герои находят 0.1 сундука/сек', en: 'Heroes find 0.1 chests/sec' },
      (L, D) => { D.scout += 0.1 * L; }),
    C('i_watch', 3, 0, 'idle', ['i_vet', 'i_scout'], 5, 12, 2, { ru: 'Ночной дозор', en: 'Night Watch' }, { ru: 'Офлайн-доход +10% и +1 ч лимита', en: 'Offline income +10% and +1h cap' },
      (L, D) => { D.offEff += 0.1 * L; D.offCap += 3600 * L; }),
    C('i_banner', 4, -1, 'idle', ['i_watch'], 5, 40, 2.2, { ru: 'Боевое знамя', en: 'War Banner' }, { ru: 'Доход героев +25%', en: 'Hero income +25%' },
      (L, D) => { D.gpsMult *= 1 + 0.25 * L; }),
    C('i_clock', 4, 1, 'idle', ['i_watch'], 5, 35, 2.2, { ru: 'Часовщик', en: 'Clockmaker' }, { ru: '+1 автоклик в секунду', en: '+1 auto click per second' },
      (L, D) => { D.autoCps += L; }),
    C('i_legion', 5, 0, 'idle', ['i_banner', 'i_clock'], 1, 200, 1, { ru: 'Легион', en: 'Legion' }, { ru: 'Каждый нанятый класс героев: всё золото +8%', en: 'Each hired hero class: all gold +8%' },
      (L, D) => { D.legion = L > 0; }),
    // Chest arm (down)
    C('h_nose', 0, 1, 'chest', ['spark'], 5, 2, 1.7, { ru: 'Нюх', en: 'Keen Nose' }, { ru: 'Сундуки чаще на 10%', en: 'Chests 10% more often' },
      (L, D) => { D.chestProg += 0.1 * L; }),
    C('h_fusion', -1, 2, 'chest', ['h_nose'], 1, 6, 1, { ru: 'Слияние', en: 'Fusion' }, { ru: 'Когда места нет — 3 одинаковых сундука сливаются в лучший', en: 'When the room is full, 3 equal chests fuse into a better one' },
      (L, D) => { D.merge = L > 0; }),
    C('h_gild', 1, 2, 'chest', ['h_nose'], 1, 5, 1, { ru: 'Позолота', en: 'Gilding' }, { ru: 'Открывает Золотые сундуки. Шанс модификатора +2%', en: 'Unlocks Golden chests. Modifier chance +2%' },
      (L, D) => { if (L) { D.mods.golden = 1; D.modChance += 0.02; } }),
    C('h_double', -2, 3, 'chest', ['h_fusion'], 5, 12, 2, { ru: 'Двойное дно', en: 'False Bottom' }, { ru: '+5% шанс двойной добычи', en: '+5% chance of double loot' },
      (L, D) => { D.double += 0.05 * L; }),
    C('h_storm', 0, 3, 'chest', ['h_gild', 'h_fusion'], 1, 15, 1, { ru: 'Зов бури', en: 'Stormcall' }, { ru: 'Открывает Грозовые сундуки', en: 'Unlocks Storm chests' },
      (L, D) => { if (L) D.mods.lightning = 1; }),
    C('h_ghost', 2, 3, 'chest', ['h_gild'], 1, 15, 1, { ru: 'Фантазм', en: 'Phantasm' }, { ru: 'Открывает Призрачные сундуки', en: 'Unlocks Ghost chests' },
      (L, D) => { if (L) D.mods.ghost = 1; }),
    C('h_frost', -1, 4, 'chest', ['h_storm'], 1, 25, 1, { ru: 'Вечный лёд', en: 'Permafrost' }, { ru: 'Открывает Ледяные сундуки', en: 'Unlocks Frozen chests' },
      (L, D) => { if (L) D.mods.frozen = 1; }),
    C('h_chroma', 1, 4, 'chest', ['h_storm', 'h_ghost'], 1, 30, 1, { ru: 'Призма', en: 'Prism' }, { ru: 'Открывает Хроматические сундуки', en: 'Unlocks Chromatic chests' },
      (L, D) => { if (L) D.mods.chromatic = 1; }),
    C('h_rate', 2, 4, 'chest', ['h_ghost'], 5, 20, 2, { ru: 'Аномалии', en: 'Anomalies' }, { ru: 'Шанс модификатора +2%', en: 'Modifier chance +2%' },
      (L, D) => { D.modChance += 0.02 * L; }),
    C('h_blaze', -2, 5, 'chest', ['h_frost'], 1, 45, 1, { ru: 'Пекло', en: 'Inferno' }, { ru: 'Открывает Пылающие сундуки', en: 'Unlocks Blazing chests' },
      (L, D) => { if (L) D.mods.blazing = 1; }),
    C('h_mimic', 0, 5, 'chest', ['h_frost', 'h_chroma'], 1, 50, 1, { ru: 'Зубастый', en: 'Toothy' }, { ru: 'Открывает Мимиков', en: 'Unlocks Mimics' },
      (L, D) => { if (L) D.mods.mimic = 1; }),
    C('h_void', 2, 5, 'chest', ['h_chroma', 'h_rate'], 1, 60, 1, { ru: 'Бездна', en: 'Abyssal' }, { ru: 'Открывает Бездонные сундуки', en: 'Unlocks Void chests' },
      (L, D) => { if (L) D.mods.void = 1; }),
    C('h_hoard', 0, 6, 'chest', ['h_blaze', 'h_mimic', 'h_void'], 1, 250, 1, { ru: 'Сокровищница', en: 'Hoard' }, { ru: 'Шанс модификатора +8%, +2 места', en: 'Modifier chance +8%, +2 slots' },
      (L, D) => { if (L) { D.modChance += 0.08; D.slots += 2; } }),
    // Arcane arm (left)
    C('a_flow', -1, 0, 'arcane', ['spark'], 5, 2, 1.7, { ru: 'Ток эссенции', en: 'Essence Flow' }, { ru: 'Эссенция +20%', en: 'Essence +20%' },
      (L, D) => { D.essMult *= 1 + 0.2 * L; }),
    C('a_hatch', -2, -1, 'arcane', ['a_flow'], 5, 10, 2, { ru: 'Гнездо', en: 'Nesting' }, { ru: 'Яйца выпадают на 15% чаще', en: 'Eggs drop 15% more often' },
      (L, D) => { D.eggMult *= 1 + 0.15 * L; }),
    C('a_slayer', -2, 1, 'arcane', ['a_flow'], 5, 8, 1.9, { ru: 'Убийца боссов', en: 'Bossbane' }, { ru: 'Урон по боссам +30%', en: 'Boss damage +30%' },
      (L, D) => { D.bossMult *= 1 + 0.3 * L; }),
    C('a_bond', -3, -1, 'arcane', ['a_hatch'], 5, 20, 2, { ru: 'Узы', en: 'Bond' }, { ru: 'Сила питомцев +15%', en: 'Pet power +15%' },
      (L, D) => { D.petMult *= 1 + 0.15 * L; }),
    C('a_time', -3, 1, 'arcane', ['a_slayer'], 3, 15, 2.2, { ru: 'Замедление', en: 'Time Dilation' }, { ru: 'Таймер босса +4 сек', en: 'Boss timer +4s' },
      (L, D) => { D.bossTime += 4 * L; }),
    C('a_wisp', -4, 0, 'arcane', ['a_bond', 'a_time'], 3, 25, 2, { ru: 'Манок', en: 'Wisp Lure' }, { ru: 'Огоньки прилетают на 20% чаще', en: 'Wisps appear 20% more often' },
      (L, D) => { D.wispRate *= 1 + 0.2 * L; }),
    C('a_nest', -4, -1, 'arcane', ['a_bond'], 2, 60, 4, { ru: 'Большое гнездо', en: 'Great Nest' }, { ru: '+1 слот питомца', en: '+1 pet slot' },
      (L, D) => { D.petSlots += L; }),
    C('a_hunt', -4, 1, 'arcane', ['a_time'], 1, 30, 1, { ru: 'Охота', en: 'The Hunt' }, { ru: 'Боссы вызываются сами, шкала босса -20%', en: 'Bosses auto-challenge, boss meter -20%' },
      (L, D) => { if (L) { D.autoBoss = true; D.bossNeed *= 0.8; } }),
    C('a_astral', -5, 0, 'arcane', ['a_nest', 'a_hunt', 'a_wisp'], 1, 220, 1, { ru: 'Астрал', en: 'Astral' }, { ru: 'Лимит зелий +5, сила зелий +50%', en: 'Potion cap +5, potion power +50%' },
      (L, D) => { if (L) { D.potCap += 5; D.potPow *= 1.5; } }),
  ];
  G.NODE_BY_ID = {}; G.NODES.forEach(n => G.NODE_BY_ID[n.id] = n);
  G.BRANCH_COLORS = { core: '#ffffff', click: '#ff6464', idle: '#63d85b', chest: '#ffd84a', arcane: '#b36bff' };

  // ---------- Stat potions (reset on ascension, like a hero's death) ----------
  G.POTIONS = [
    { id: 'att',  short: 'ATT', color: '#e04cf0', name: { ru: 'Атака', en: 'Attack' },     desc: { ru: 'Урон героя и клик +5%', en: 'Hero damage and clicks +5%' } },
    { id: 'def',  short: 'DEF', color: '#9a9aa6', name: { ru: 'Защита', en: 'Defense' },   desc: { ru: 'Прочность кнопки +8%', en: 'Button toughness +8%' } },
    { id: 'spd',  short: 'SPD', color: '#41d65b', name: { ru: 'Скорость', en: 'Speed' },   desc: { ru: 'Автоклики и голем +5%', en: 'Auto clicks and golem +5%' } },
    { id: 'dex',  short: 'DEX', color: '#ff9b2d', name: { ru: 'Ловкость', en: 'Dexterity' }, desc: { ru: 'Шанс крита +0.5%', en: 'Crit chance +0.5%' } },
    { id: 'vit',  short: 'VIT', color: '#e0413b', name: { ru: 'Живучесть', en: 'Vitality' }, desc: { ru: 'Доход героев +5%', en: 'Hero income +5%' } },
    { id: 'wis',  short: 'WIS', color: '#3fa0ff', name: { ru: 'Мудрость', en: 'Wisdom' },  desc: { ru: 'Эссенция +5%', en: 'Essence +5%' } },
    { id: 'life', short: 'LIFE', color: '#ff7aa8', name: { ru: 'Жизнь', en: 'Life' },      desc: { ru: 'Всё золото +3%', en: 'All gold +3%' } },
    { id: 'mana', short: 'MANA', color: '#6a7bff', name: { ru: 'Мана', en: 'Mana' },       desc: { ru: 'Сила питомцев +4%', en: 'Pet power +4%' } },
  ];

  // ---------- Pets (gacha "cuties") ----------
  // tier: 0 common, 1 rare, 2 legendary, 3 divine. cps = auto clicks/sec at level 1.
  G.PET_TIERS = [
    { name: { ru: 'Обычный', en: 'Common' }, color: '#c7b299', rate: 0.62 },
    { name: { ru: 'Редкий', en: 'Rare' }, color: '#4fa8ff', rate: 0.28 },
    { name: { ru: 'Легендарный', en: 'Legendary' }, color: '#ffa033', rate: 0.09 },
    { name: { ru: 'Божественный', en: 'Divine' }, color: '#ffffff', rate: 0.01 },
  ];
  G.PETS = [
    { id: 'slime',   tier: 0, cps: 1,   name: { ru: 'Слизик', en: 'Goop' },         desc: { ru: 'Автоклики', en: 'Auto clicks' } },
    { id: 'bat',     tier: 0, cps: 0,   name: { ru: 'Кусь', en: 'Nibbles' },        desc: { ru: 'Шанс крита', en: 'Crit chance' },   fx: (p, D) => { D.crit += 0.004 * p; } },
    { id: 'frog',    tier: 0, cps: 0,   name: { ru: 'Квакша', en: 'Croaky' },       desc: { ru: 'Удача', en: 'Luck' },                fx: (p, D) => { D.luck += 0.01 * p; } },
    { id: 'beetle',  tier: 0, cps: 0,   name: { ru: 'Скарабей', en: 'Scarab' },     desc: { ru: 'Доход героев', en: 'Hero income' },  fx: (p, D) => { D.gpsMult *= 1 + 0.05 * p; } },
    { id: 'owl',     tier: 1, cps: 0,   name: { ru: 'Совушка', en: 'Hoot' },        desc: { ru: 'Эссенция', en: 'Essence' },          fx: (p, D) => { D.essMult *= 1 + 0.04 * p; } },
    { id: 'boo',     tier: 1, cps: 1.5, name: { ru: 'Бу', en: 'Boo' },              desc: { ru: 'Автоклики, шанс модификатора', en: 'Auto clicks, modifier chance' }, fx: (p, D) => { D.modChance += 0.003 * p; } },
    { id: 'imp',     tier: 1, cps: 0,   name: { ru: 'Уголёк', en: 'Ember' },        desc: { ru: 'Урон по боссам', en: 'Boss damage' }, fx: (p, D) => { D.bossMult *= 1 + 0.08 * p; } },
    { id: 'pebble',  tier: 1, cps: 0,   name: { ru: 'Камушек', en: 'Pebble' },      desc: { ru: 'Открывает сундуки', en: 'Opens chests' }, fx: (p, D) => { D.petOpen += 0.12 * p; } },
    { id: 'phoenix', tier: 2, cps: 3,   name: { ru: 'Феникс', en: 'Phoenix' },      desc: { ru: 'Автоклики, сила крита', en: 'Auto clicks, crit power' }, fx: (p, D) => { D.critMult += 0.5 * p; } },
    { id: 'drake',   tier: 2, cps: 0,   name: { ru: 'Дракоша', en: 'Drakey' },      desc: { ru: 'Всё золото', en: 'All gold' },       fx: (p, D) => { D.goldMult *= 1 + 0.06 * p; } },
    { id: 'starfox', tier: 2, cps: 0,   name: { ru: 'Звёздный лис', en: 'Starfox' }, desc: { ru: 'Яйца и удача', en: 'Eggs and luck' }, fx: (p, D) => { D.eggMult *= 1 + 0.08 * p; D.luck += 0.01 * p; } },
    { id: 'buttonling', tier: 3, cps: 4, name: { ru: 'Кнопыш', en: 'Buttonling' },  desc: { ru: 'Всё понемногу', en: 'A bit of everything' }, fx: (p, D) => { D.goldMult *= 1 + 0.1 * p; D.luck += 0.015 * p; } },
  ];
  G.PET_BY_ID = {}; G.PETS.forEach(p => G.PET_BY_ID[p.id] = p);
  G.PET_MAX_LEVEL = 25;
  G.GOLDEN_CHANCE = 0.05;

  // ---------- Realms & bosses ----------
  G.REALM_SIZE = 5; // depths per realm; the 5th depth is the realm lord
  G.REALMS = [
    { id: 'shore',     name: { ru: 'Берег', en: 'Shoreline' },       minion: 'b_crab',   lord: 'l_crab',
      minionName: { ru: 'Песчаный краб', en: 'Sand Crab' },     lordName: { ru: 'Король-краб', en: 'The Crab King' } },
    { id: 'meadow',    name: { ru: 'Луга', en: 'Meadows' },          minion: 'b_goblin', lord: 'l_goblin',
      minionName: { ru: 'Гоблин', en: 'Goblin' },               lordName: { ru: 'Вождь гоблинов', en: 'Goblin Warchief' } },
    { id: 'forest',    name: { ru: 'Чаща', en: 'Deepwood' },         minion: 'b_shroom', lord: 'l_tree',
      minionName: { ru: 'Грибняк', en: 'Shroomling' },          lordName: { ru: 'Древний Ент', en: 'Elder Treant' } },
    { id: 'highlands', name: { ru: 'Нагорье', en: 'Highlands' },     minion: 'b_golem',  lord: 'l_titan',
      minionName: { ru: 'Каменный голем', en: 'Stone Golem' },  lordName: { ru: 'Горный титан', en: 'Mountain Titan' } },
    { id: 'tundra',    name: { ru: 'Снега', en: 'Frostlands' },      minion: 'b_yeti',   lord: 'l_wyrm',
      minionName: { ru: 'Йети', en: 'Yeti' },                   lordName: { ru: 'Ледяной змей', en: 'Frost Wyrm' } },
    { id: 'godlands',  name: { ru: 'Земли богов', en: 'Godlands' },  minion: 'b_eye',    lord: 'l_eye',
      minionName: { ru: 'Глазун', en: 'Watcher' },              lordName: { ru: 'Всевидящее Око', en: 'The All-Seeing Eye' } },
    { id: 'abyss',     name: { ru: 'Бездна', en: 'Abyss' },          minion: 'b_imp',    lord: 'l_demon',
      minionName: { ru: 'Бес', en: 'Fiend' },                   lordName: { ru: 'Владыка демонов', en: 'Demon Lord' } },
    { id: 'void',      name: { ru: 'Пустота', en: 'The Void' },      minion: 'b_wraith', lord: 'l_button',
      minionName: { ru: 'Призрак пустоты', en: 'Void Wraith' },  lordName: { ru: 'Безумная Кнопка', en: 'The Mad Button' } },
  ];

  // ---------- Legacy: permanent upgrades bought with Fame ----------
  G.LEGACY = [
    { id: 'lg_click', base: 1, growth: 1.6, max: 25, name: { ru: 'Наследие силы', en: 'Ancestral Might' }, desc: { ru: 'Клик и урон героя +40%', en: 'Clicks and hero damage +40%' },
      fx: (L, D) => { D.clickMult *= 1 + 0.4 * L; D.heroMult *= 1 + 0.4 * L; } },
    { id: 'lg_guild', base: 1, growth: 1.6, max: 25, name: { ru: 'Наследие гильдии', en: 'Ancestral Guild' }, desc: { ru: 'Доход героев +40%', en: 'Hero income +40%' },
      fx: (L, D) => { D.gpsMult *= 1 + 0.4 * L; } },
    { id: 'lg_start', base: 2, growth: 2, max: 8, name: { ru: 'Фора', en: 'Head Start' }, desc: { ru: 'Старт с золотом: 100 × 10^ур.', en: 'Start with 100 × 10^lvl gold' },
      fx: () => {} },
    { id: 'lg_luck', base: 3, growth: 1.8, max: 10, name: { ru: 'Счастливая звезда', en: 'Lucky Star' }, desc: { ru: 'Удача +3%', en: 'Luck +3%' },
      fx: (L, D) => { D.luck += 0.03 * L; } },
    { id: 'lg_boss', base: 3, growth: 1.7, max: 15, name: { ru: 'Гроза боссов', en: 'Boss Slayer' }, desc: { ru: 'Урон по боссам +35%', en: 'Boss damage +35%' },
      fx: (L, D) => { D.bossMult *= 1 + 0.35 * L; } },
    { id: 'lg_pot', base: 4, growth: 2, max: 10, name: { ru: 'Погреб зелий', en: 'Potion Cellar' }, desc: { ru: 'Лимит каждого зелья +3', en: 'Each potion cap +3' },
      fx: (L, D) => { D.potCap += 3 * L; } },
    { id: 'lg_keeppot', base: 12, growth: 2.5, max: 4, name: { ru: 'Семейный сундук', en: 'Family Vault' }, desc: { ru: 'Сохранять 25% зелий при вознесении', en: 'Keep 25% of potions on ascension' },
      fx: () => {} },
    { id: 'lg_stars', base: 6, growth: 2, max: 5, name: { ru: 'Память звёзд', en: 'Star Memory' }, desc: { ru: 'Старт с 12% эссенции прошлого забега', en: 'Start with 12% of last run\'s essence' },
      fx: () => {} },
    { id: 'lg_fusion', base: 15, growth: 1, max: 1, name: { ru: 'Вечное слияние', en: 'Eternal Fusion' }, desc: { ru: 'Слияние и Позолота открыты с начала', en: 'Fusion and Gilding unlocked from the start' },
      fx: (L, D) => { if (L) { D.merge = true; D.mods.golden = 1; } } },
    { id: 'lg_deep', base: 8, growth: 2.2, max: 10, name: { ru: 'Глубокое погружение', en: 'Deep Dive' }, desc: { ru: 'Начинать на 2 глубины ниже', en: 'Start 2 depths deeper' },
      fx: () => {} },
    { id: 'lg_pet', base: 10, growth: 3, max: 2, name: { ru: 'Переноска', en: 'Pet Carrier' }, desc: { ru: '+1 слот питомца', en: '+1 pet slot' },
      fx: (L, D) => { D.petSlots += L; } },
    { id: 'lg_time', base: 5, growth: 2, max: 5, name: { ru: 'Искривление времени', en: 'Time Warp' }, desc: { ru: 'Офлайн: +2 ч лимита, +10% эффективности', en: 'Offline: +2h cap, +10% efficiency' },
      fx: (L, D) => { D.offCap += 7200 * L; D.offEff += 0.1 * L; } },
    { id: 'lg_fame', base: 10, growth: 2, max: 10, name: { ru: 'Громкое имя', en: 'Renown' }, desc: { ru: 'Слава +15%', en: 'Fame gain +15%' },
      fx: (L, D) => { D.fameMult *= 1 + 0.15 * L; } },
    { id: 'lg_quest', base: 5, growth: 2, max: 4, name: { ru: 'Мастер заданий', en: 'Quest Master' }, desc: { ru: 'Награды заданий +35%', en: 'Quest rewards +35%' },
      fx: (L, D) => { D.questMult *= 1 + 0.35 * L; } },
    { id: 'lg_gold', base: 12, growth: 2.5, max: 4, name: { ru: 'Золотое касание', en: 'Golden Touch' }, desc: { ru: 'Шанс золотого питомца +2%', en: 'Golden pet chance +2%' },
      fx: (L, D) => { D.goldenChance += 0.02 * L; } },
  ];
  G.LEGACY_BY_ID = {}; G.LEGACY.forEach(l => G.LEGACY_BY_ID[l.id] = l);

  // ---------- Button skins ----------
  G.SKINS = [
    { id: 'classic',  base: '#e8413c', name: { ru: 'Классика', en: 'Classic' },   unlock: null },
    { id: 'emerald',  base: '#2fc46a', name: { ru: 'Изумруд', en: 'Emerald' },    unlock: 'chests_100' },
    { id: 'sapphire', base: '#3f7bff', name: { ru: 'Сапфир', en: 'Sapphire' },    unlock: 'depth_10' },
    { id: 'amethyst', base: '#a048ff', name: { ru: 'Аметист', en: 'Amethyst' },   unlock: 'asc_1' },
    { id: 'gold',     base: '#ffc629', name: { ru: 'Золото', en: 'Gold' },        unlock: 'gold_1e9' },
    { id: 'obsidian', base: '#3a3348', name: { ru: 'Обсидиан', en: 'Obsidian' },  unlock: 'madbutton' },
    { id: 'rainbow',  base: 'rainbow', name: { ru: 'Радуга', en: 'Rainbow' },     unlock: 'all_items' },
    { id: 'divine',   base: '#f4f6ff', name: { ru: 'Божественная', en: 'Divine' }, unlock: 'first_divine' },
  ];

  // ---------- Wisp buffs (golden-cookie style event) ----------
  G.WISP_EFFECTS = [
    { id: 'frenzy', w: 40, name: { ru: 'Неистовство! Золото ×7', en: 'Frenzy! Gold ×7' }, dur: 20 },
    { id: 'rain',   w: 24, name: { ru: 'Дождь сундуков!', en: 'Chest Rain!' } },
    { id: 'lucky',  w: 24, name: { ru: 'Удача! Мешок золота', en: 'Lucky! A sack of gold' } },
    { id: 'storm',  w: 10, name: { ru: 'Буря кликов! Клик ×77', en: 'Click Storm! Click ×77' }, dur: 10 },
    { id: 'egg',    w: 2,  name: { ru: 'Яйцо питомца!', en: 'A pet egg!' } },
  ];

  // ---------- Daily login rewards (7-day cycle) ----------
  G.DAILY = [
    { kind: 'gold', mins: 10 }, { kind: 'eggs', n: 2 }, { kind: 'gold', mins: 30 }, { kind: 'ess', n: 25 },
    { kind: 'eggs', n: 4 }, { kind: 'gold', mins: 90 }, { kind: 'chest', tier: 6 },
  ];
})(globalThis.G = globalThis.G || {});

/* js/game.js */
// BTTN — game logic. No DOM access here: this file also runs in the Node
// balance simulator (tools/sim.js). It changes G.S and emits events.
(function (G) {
  'use strict';
  const { clamp, chance, weighted, pick, rand, emit } = G;

  const TUNE = G.TUNE = {
    chestNeed: 10,          // clicks per chest before upgrades
    autoChestFactor: 0.1,   // auto clicks give less chest progress than real ones
    depthGold: 1.08,        // gold multiplier per depth
    bossBase: 400,          // boss hp at depth 0
    bossGrowth: 2.5,        // boss hp growth per depth
    lordHp: 4,
    heroBossPct: 0.35,      // share of hero income dealt to bosses as dps
    comboTime: 1.25,
    maxManualCps: 25,
    wispMin: 50, wispMax: 120, wispLife: 13,
    mimicClicks: 15, mimicLife: 8, mimicIdle: 30,
    blazeLife: 6,
  };

  // ---------- State ----------
  function potZero() { const o = {}; G.POTIONS.forEach(p => o[p.id] = 0); return o; }
  function newState() {
    return {
      v: 1, created: Date.now(), lastSave: Date.now(),
      gold: 0, goldRun: 0, goldTotal: 0,
      clicks: 0, clicksRun: 0,
      upg: {}, heroes: {}, nodes: {}, legacy: {},
      essence: 0, essRun: 0, lastRunEss: 0,
      depth: 0, maxDepth: 0, bestDepth: 0,
      pots: potZero(),
      chests: [], chestMeter: 0, bossMeter: 0, uid: 0,
      buffs: [],
      coll: {}, opened: [0, 0, 0, 0, 0, 0, 0], modsSeen: {},
      pets: {}, active: [], eggs: 0, pity: { l: 0, d: 0 }, pulls: 0,
      fame: 0, fameTotal: 0, ascensions: 0,
      ach: {}, skin: 'classic',
      quests: [], questsDone: 0, rerollAt: 0,
      daily: { last: '', streak: 0 },
      st: { crits: 0, bossKills: 0, lordKills: 0, wisps: 0, mimics: 0, merges: 0, divine: 0, maxCombo: 0,
        playTime: 0, chests: 0, modded: 0, megas: 0 },
      set: { sound: 1, music: 1, vol: 0.6, lang: '', hold: 0, shake: 1, autoBoss: 1 },
      seen: {}, tut: 0,
    };
  }
  G.newState = () => { const s = newState(); if (G.ensureHero) G.ensureHero(s); return s; };
  G.S = newState();

  // Runtime-only state (not saved)
  const R = G.R = {
    combo: 0, comboT: 0, autoAcc: 0, golemAcc: 0, petOpenAcc: 0,
    wisp: null, wispT: 40, manualTimes: [], achT: 0, recalcT: 0, dirty: true,
    boss: null, bossReady: false,
  };

  // ---------- Derived stats ----------
  const D = G.D = {};
  function baseD() {
    return {
      clickAdd: 1, clickMult: 1, clickGpsPct: 0, gpsMult: 1, goldMult: 1, itemMult: 1,
      crit: 0.03, critMult: 3, chestProg: 1, chestNeed: TUNE.chestNeed, slots: 6, autoOpen: 0, luck: 0,
      comboCap: 50, comboPer: 0.005, autoCps: 0, essMult: 1, modChance: 0, mods: {}, merge: false, double: 0,
      bossMult: 1, bossTime: 30, petMult: 1, petSlots: 2, eggMult: 1, wispRate: 1, buffDur: 1,
      offCap: 7200, offEff: 0.5, scout: 0, vet: 0, legion: false, mega: false, autoBoss: false, bossNeed: 25,
      potCap: 10, potPow: 1, fameMult: 1, questMult: 1, goldenChance: G.GOLDEN_CHANCE, petOpen: 0, spdMult: 1,
      heroMult: 1, hpMult: 1,
    };
  }

  function stars(n) { let s = 0; for (const t of G.STAR_THRESHOLDS) if (n >= t) s++; return s; }
  G.stars = stars;

  function heroMilestones(n) { let m = 0; for (const t of G.HERO_MILESTONES) if (n >= t) m++; return m; }
  G.heroMilestones = heroMilestones;

  function petPower(st) { return (1 + 0.15 * (st.lvl - 1)) * (st.gold ? 1.5 : 1); }
  function petCps(pet, st) { return pet.cps * (1 + 0.1 * (st.lvl - 1)) * (st.gold ? 1.5 : 1); }
  G.petPower = petPower; G.petCps = petCps;

  function hasBuff(id) { return G.S.buffs.some(b => b.id === id); }
  G.hasBuff = hasBuff;

  function recalc() {
    const S = G.S;
    const d = baseD();
    for (const u of G.UPGRADES) { const L = S.upg[u.id] || 0; if (L) u.fx(L, d); }
    for (const n of G.NODES) { const L = S.nodes[n.id] || 0; if (L) n.fx(L, d); }
    for (const l of G.LEGACY) { const L = S.legacy[l.id] || 0; if (L) l.fx(L, d); }
    if (G.heroEcon) G.heroEcon(d);

    // Collection bonuses
    const sums = {};
    for (const it of G.ITEMS) {
      const s = stars(S.coll[it.id] || 0);
      if (s) sums[it.bonus] = (sums[it.bonus] || 0) + G.BONUS[it.bonus].v * G.RARITIES[it.r].bonusMul * s;
    }
    const sm = k => sums[k] || 0;
    d.clickMult *= 1 + sm('click'); d.gpsMult *= 1 + sm('gps'); d.goldMult *= 1 + sm('gold');
    d.crit += sm('crit'); d.critMult += sm('critd'); d.luck += sm('luck'); d.essMult *= 1 + sm('ess');
    d.itemMult *= 1 + sm('item'); d.bossMult *= 1 + sm('boss'); d.chestProg += sm('chest');
    d.eggMult *= 1 + sm('egg'); d.petMult *= 1 + sm('pet'); d.comboCap += Math.floor(sm('combo'));
    d.collSums = sums;

    // Potions
    const P = S.pots, pp = d.potPow;
    d.clickMult *= 1 + 0.05 * P.att * pp; d.heroMult *= 1 + 0.05 * P.att * pp; d.hpMult *= 1 + 0.08 * P.def * pp;
    d.spdMult *= 1 + 0.05 * P.spd * pp; d.crit += 0.005 * P.dex * pp;
    d.gpsMult *= 1 + 0.05 * P.vit * pp; d.essMult *= 1 + 0.05 * P.wis * pp;
    d.goldMult *= 1 + 0.03 * P.life * pp; d.petMult *= 1 + 0.04 * P.mana * pp;

    // Achievements & fame
    d.achCount = Object.keys(S.ach).length;
    d.goldMult *= 1 + 0.01 * d.achCount;
    d.goldMult *= 1 + 0.01 * S.fameTotal;

    // Heroes
    let total = 0, classes = 0;
    for (const h of G.HEROES) { const n = S.heroes[h.id] || 0; total += n; if (n) classes++; }
    d.heroTotal = total; d.heroClasses = classes;
    if (d.legion) d.goldMult *= 1 + 0.08 * classes;
    if (d.vet) d.gpsMult *= 1 + d.vet * Math.floor(total / 10);

    // Pets (after petMult is final)
    d.petCps = 0;
    const slots = d.petSlots;
    S.active = S.active.filter(id => S.pets[id]).slice(0, slots);
    for (const id of S.active) {
      const pet = G.PET_BY_ID[id], st = S.pets[id];
      const p = petPower(st) * d.petMult;
      if (pet.fx) pet.fx(p, d);
      if (pet.cps) d.petCps += petCps(pet, st) * Math.sqrt(d.petMult);
    }
    d.crit = Math.min(0.9, d.crit);
    d.petCps *= d.spdMult; d.autoCps *= d.spdMult; d.petOpen *= d.spdMult;
    if (d.autoOpen) d.autoOpen /= d.spdMult;
    d.comboCap = Math.floor(d.comboCap);

    d.depthMult = Math.pow(TUNE.depthGold, S.depth);
    const buffGold = hasBuff('frenzy') ? 7 : 1, buffClick = hasBuff('storm') ? 77 : 1;
    d.buffGold = buffGold; d.buffClick = buffClick;

    let heroGps = 0;
    d.heroGps = {};
    for (const h of G.HEROES) {
      const n = S.heroes[h.id] || 0;
      if (!n) continue;
      const g = n * h.gps * Math.pow(2, heroMilestones(n)) * d.gpsMult * d.goldMult * d.depthMult;
      d.heroGps[h.id] = g; heroGps += g;
    }
    d.gpsBase = heroGps;
    d.gps = heroGps * buffGold;
    const clickCore = d.clickAdd * d.clickMult * d.goldMult * d.depthMult;
    d.clickBase = clickCore + d.gpsBase * d.clickGpsPct;
    d.click = (clickCore * buffGold + d.gps * d.clickGpsPct) * buffClick;
    d.incomeRef = Math.max(1, d.gps + (clickCore * buffGold + d.gps * d.clickGpsPct) * 3);
    d.effLuck = d.luck + S.depth * 0.003;
    if (G.heroFinish) G.heroFinish(d);
    Object.keys(D).forEach(k => delete D[k]);
    Object.assign(D, d);
    R.dirty = false;
  }
  G.recalc = recalc;
  G.dirty = () => { R.dirty = true; };

  // ---------- Money ----------
  function addGold(n, src) {
    if (!(n > 0)) return;
    const S = G.S;
    S.gold += n; S.goldRun += n; S.goldTotal += n;
    if (G.goldBySrc) G.goldBySrc[src || '?'] = (G.goldBySrc[src || '?'] || 0) + n;
    questProgress('gold', n);
  }
  G.addGold = addGold;
  function addEssence(n, src) {
    if (!(n > 0)) return;
    if (G.essBySrc) G.essBySrc[src || '?'] = (G.essBySrc[src || '?'] || 0) + n;
    G.S.essence += n; G.S.essRun += n;
    emit('essence', n);
  }
  G.addEssence = addEssence;
  function addEggs(n) {
    n = Math.floor(n);
    if (n <= 0) return 0;
    G.S.eggs += n;
    emit('eggs', n);
    return n;
  }
  function rollCount(expected) { // expected value -> integer with random rounding
    const f = Math.floor(expected);
    return f + (chance(expected - f) ? 1 : 0);
  }

  // ---------- Clicking ----------
  function critRoll() { return chance(D.crit); }

  function manualClick(x, y) {
    const S = G.S;
    const now = performance.now();
    const mt = R.manualTimes;
    while (mt.length && now - mt[0] > 1000) mt.shift();
    if (mt.length >= TUNE.maxManualCps) return null;
    mt.push(now);

    S.clicks++; S.clicksRun++;
    R.combo = Math.min(D.comboCap, R.combo + 1);
    R.comboT = TUNE.comboTime;
    if (R.combo > S.st.maxCombo) S.st.maxCombo = R.combo;
    const crit = critRoll();
    const mega = D.mega && S.clicks % 25 === 0;
    let gain = D.click * (1 + R.combo * D.comboPer);
    if (crit) { gain *= D.critMult; S.st.crits++; questProgress('crit', 1); }
    if (mega) { gain *= 30; S.st.megas++; }
    addGold(gain, 'click');
    const dmg = R.boss ? D.heroHit * TUNE.clickVolley : 0;
    if (G.heroVolley && !(R.stun > 0)) G.heroVolley(TUNE.clickVolley, 'click');
    S.chestMeter += D.chestProg;
    spawnFromMeter();
    questProgress('clicks', 1);
    questProgress('combo', R.combo, true);
    const ev = { gain, crit, mega, x, y, combo: R.combo, dmg };
    emit('click', ev);
    return ev;
  }
  G.manualClick = manualClick;

  // Auto clicks are aggregated: expected crit value, no combo.
  function autoClicks(n, dt) {
    if (n <= 0) return;
    const critEV = 1 + D.crit * (D.critMult - 1);
    const gain = D.click * critEV * n;
    addGold(gain, 'auto');
    const petN = n * D.petCps / Math.max(1e-9, D.autoCps + D.petCps);
    if (G.heroVolley && petN > 0) G.heroVolley(TUNE.petVolley * petN, 'pet');
    G.S.chestMeter += D.chestProg * TUNE.autoChestFactor * n;
    emit('autoClicks', n, gain);
  }

  // ---------- Chests ----------
  function rollTier() {
    const L = 1 + D.effLuck;
    const w = G.CHEST_WEIGHTS.map((b, i) => b * Math.pow(L, i * 0.5));
    return weighted(w);
  }
  function rollMod() {
    const ids = Object.keys(D.mods);
    if (!ids.length) return null;
    let p = 0.06 + D.modChance;
    if (!chance(p)) return null;
    return pick(ids);
  }
  function rollRarity(tier, rolls) {
    let best = 0;
    for (let i = 0; i < rolls; i++) {
      let r = tier;
      if (r < 6 && chance(0.12)) r++;
      if (r > best) best = r;
    }
    return best;
  }
  function pickItem(r) {
    const list = G.ITEMS_BY_RARITY[r];
    return list[weighted(list.map(i => i.w))];
  }
  function itemValue(it) {
    return D.incomeRef * G.RARITIES[it.r].secs * it.m * D.itemMult;
  }
  G.itemValue = itemValue;
  function chestValue(tier) { return D.incomeRef * G.RARITIES[tier].secs * D.itemMult; }

  function tryMerge() {
    const S = G.S;
    for (let t = 0; t < 6; t++) {
      const same = S.chests.filter(c => c.tier === t && !c.mod);
      if (same.length >= 3) {
        const parts = same.slice(0, 3);
        S.chests = S.chests.filter(c => !parts.includes(c));
        const nc = makeChest(t + 1, null);
        nc.merged = true;
        S.chests.push(nc);
        S.st.merges++;
        emit('merge', parts, nc);
        return true;
      }
    }
    return false;
  }

  function makeChest(tier, mod) {
    const S = G.S;
    const c = { id: ++S.uid, tier, mod: mod || null, age: 0 };
    if (mod === 'frozen') c.hp = 8;
    if (mod === 'blazing') c.life = TUNE.blazeLife;
    if (mod === 'mimic') { c.hp = TUNE.mimicClicks; c.awake = false; }
    return c;
  }

  function spawnChest(tier, mod, fromBoss) {
    const S = G.S;
    if (tier === undefined || tier === null) tier = rollTier();
    if (mod === undefined) mod = rollMod();
    if (mod === 'chromatic') tier = Math.min(6, tier + 1);
    if (S.chests.length >= D.slots) {
      if (!(D.merge && tryMerge())) {
        // No room: the chest is sold unopened at a discount.
        const v = chestValue(tier) * 0.3;
        addGold(v, 'spill');
        emit('spill', tier, v);
        return null;
      }
    }
    const c = makeChest(tier, mod);
    S.chests.push(c);
    if (mod) S.modsSeen[mod] = 1;
    emit('chestSpawn', c, fromBoss);
    return c;
  }
  G.spawnChest = spawnChest;

  function spawnFromMeter() {
    const S = G.S;
    let guard = 0;
    while (S.chestMeter >= D.chestNeed && guard++ < 40) {
      S.chestMeter -= D.chestNeed;
      spawnChest();
    }
    if (S.chestMeter > D.chestNeed * 40) S.chestMeter = 0;
  }

  // Opens a chest (on the field or virtual). Returns loot summary.
  function openChest(c, source, depthGuard) {
    const S = G.S;
    const idx = S.chests.indexOf(c);
    if (idx >= 0) S.chests.splice(idx, 1);
    let n = 1;
    if (c.mod === 'ghost') n = 2;
    if (c.mod === 'frozen') n = 3;
    if (c.mod === 'mimic') n = 5;
    if (D.double && chance(D.double)) n *= 2;
    const rolls = c.mod === 'chromatic' ? 3 : 1;
    const loot = { items: [], gold: 0, ess: 0, eggs: 0, pots: [], tier: c.tier, mod: c.mod, chest: c, source };
    const valMult = c.mod === 'blazing' ? 5 : 1;
    for (let i = 0; i < n; i++) {
      const it = pickItem(rollRarity(c.tier, rolls));
      const before = S.coll[it.id] || 0;
      S.coll[it.id] = before + 1;
      const v = itemValue(it) * valMult;
      loot.gold += v;
      loot.items.push({ it, v, isNew: before === 0, star: stars(before + 1) > stars(before) });
      if (it.r === 6) { S.st.divine++; }
      if (stars(before + 1) > stars(before)) R.dirty = true;
      if (G.gainGear) G.gainGear(it, c.tier);
      questProgress('rarity', it.r);
    }
    if (c.mod === 'golden') loot.gold += D.incomeRef * 8 * (c.tier + 1);
    addGold(loot.gold, 'chest');
    let e = G.RARITIES[c.tier].ess * D.essMult * (c.mod === 'void' ? 10 : 1);
    if (c.mod === 'void') e = Math.max(e, 1 * D.essMult);
    loot.ess = e; addEssence(e, 'chest' + c.tier);
    if (c.tier >= 4 && chance(0.02 * (c.tier - 3) * D.eggMult)) loot.eggs += addEggs(1);
    if (c.tier >= 4 && chance(0.02 * (c.tier - 3))) { const p = givePotion(); if (p) loot.pots.push(p); }
    S.opened[c.tier]++;
    S.st.chests++;
    if (c.mod) { S.st.modded++; questProgress('mod', 1); }
    questProgress('chests', 1);
    emit('chestOpen', loot);
    if (c.mod === 'lightning' && !depthGuard) {
      const targets = S.chests.filter(o => o.mod !== 'mimic' && o.mod !== 'frozen').slice(0, 3);
      emit('lightning', c, targets);
      targets.forEach(t => openChest(t, 'chain', true));
    }
    return loot;
  }
  G.openChest = openChest;

  // Player tapped a chest on the field.
  function clickChest(c) {
    const S = G.S;
    if (!S.chests.includes(c)) return;
    if (c.mod === 'frozen') {
      c.hp -= critRoll() ? 3 : 1;
      emit('chestHit', c);
      if (c.hp <= 0) openChest(c, 'hand');
      return;
    }
    if (c.mod === 'mimic') {
      if (!c.awake) { c.awake = true; c.life = TUNE.mimicLife; emit('mimicWake', c); return; }
      c.hp -= critRoll() ? 3 : 1;
      emit('chestHit', c);
      if (c.hp <= 0) { S.st.mimics++; if (chance(0.5 * D.eggMult)) addEggs(1); openChest(c, 'hand'); }
      return;
    }
    openChest(c, 'hand');
  }
  G.clickChest = clickChest;

  function golemPick() {
    const S = G.S;
    const list = S.chests.filter(c => c.mod !== 'mimic');
    if (!list.length) return null;
    return list.find(c => c.mod === 'blazing') || list.find(c => c.mod === 'frozen') ||
      list.reduce((a, b) => (b.tier > a.tier ? b : a), list[0]);
  }
  function golemAct() {
    const c = golemPick();
    if (!c) return false;
    emit('golem', c);
    if (c.mod === 'frozen') { c.hp -= 2; emit('chestHit', c); if (c.hp <= 0) openChest(c, 'golem'); }
    else openChest(c, 'golem');
    return true;
  }

  // ---------- Potions ----------
  function givePotion(id) {
    const S = G.S;
    const avail = G.POTIONS.filter(p => S.pots[p.id] < D.potCap);
    if (!avail.length) { addEssence(10 * D.essMult, 'potion'); emit('potionFull'); return null; }
    const p = id ? G.POTIONS.find(x => x.id === id && S.pots[x.id] < D.potCap) || pick(avail) : pick(avail);
    S.pots[p.id]++;
    R.dirty = true;
    emit('potion', p);
    return p;
  }
  G.givePotion = givePotion;

  // ---------- Bosses ----------
  function realmIndex(d) { return Math.min(G.REALMS.length - 1, Math.floor(d / G.REALM_SIZE)); }
  G.realmIndex = realmIndex;
  function isLord(d) { return d % G.REALM_SIZE === G.REALM_SIZE - 1; }
  G.isLord = isLord;
  function bossHp(d) {
    return TUNE.bossBase * Math.pow(TUNE.bossGrowth, d) * (isLord(d) ? TUNE.lordHp : 1);
  }
  G.bossHp = bossHp;
  function bossName(d) {
    const r = G.REALMS[realmIndex(d)];
    return isLord(d) ? r.lordName : r.minionName;
  }
  G.bossName = bossName;

  function startBoss() {
    const S = G.S;
    if (R.boss || !R.bossReady) return false;
    const d = S.depth;
    const lord = isLord(d);
    const hp = G.bossHp(d);
    if (G.heroBossStart) G.heroBossStart();
    R.boss = { d, lord, hp, max: hp, t: D.bossTime + (lord ? 15 : 0), T: D.bossTime + (lord ? 15 : 0),
      realm: realmIndex(d), sprite: lord ? G.REALMS[realmIndex(d)].lord : G.REALMS[realmIndex(d)].minion };
    R.bossReady = false;
    emit('bossStart', R.boss);
    return true;
  }
  G.startBoss = startBoss;

  function hitBoss(dmg) {
    const b = R.boss;
    if (!b || b.dead) return;
    b.hp -= dmg;
    if (b.hp <= 0) bossWin();
  }
  G.hitBoss = hitBoss;

  function bossWin() {
    const S = G.S, b = R.boss;
    b.dead = true;
    const d = b.d;
    const first = S.st.bossKills === 0;
    if (d === 39 && S.rec && !S.rec.madTime) S.rec.madTime = S.st.playTime;
    S.st.bossKills++;
    if (b.lord) S.st.lordKills++;
    const rew = { gold: D.incomeRef * (b.lord ? 40 : 10), ess: (2 + d * 0.3) * (b.lord ? 3 : 1) * D.essMult,
      eggs: 0, pots: [], chests: [], lord: b.lord, d };
    addGold(rew.gold, 'boss');
    addEssence(rew.ess, 'boss');
    let eggEV = (b.lord ? 1 + Math.floor(d / 15) : 0.15) * D.eggMult;
    rew.eggs = addEggs(rollCount(eggEV) + (first ? 1 : 0));
    const pots = b.lord ? 1 : (chance(0.15) ? 1 : 0);
    for (let i = 0; i < pots; i++) { const p = givePotion(); if (p) rew.pots.push(p); }
    const tier = b.lord ? Math.min(6, 1 + Math.floor(d / 8)) : Math.min(5, Math.floor(d / 8));
    const count = b.lord ? 2 : 1;
    S.depth++;
    if (S.depth > S.maxDepth) S.maxDepth = S.depth;
    if (S.depth > S.bestDepth) S.bestDepth = S.depth;
    S.bossMeter = 0;
    R.boss = null;
    R.dirty = true;
    recalc();
    for (let i = 0; i < count; i++) rew.chests.push(openChest(makeChest(tier, null), 'boss'));
    questProgress('boss', 1);
    emit('bossWin', rew, b);
    if (realmIndex(S.depth) !== realmIndex(d)) emit('realm', realmIndex(S.depth));
  }

  function bossFail() {
    const S = G.S, b = R.boss;
    R.boss = null;
    S.bossMeter = Math.floor(D.bossNeed * 0.5);
    emit('bossFail', b);
  }
  G.fleeBoss = () => { if (R.boss) bossFail(); };

  // ---------- Wisps ----------
  function spawnWisp() {
    R.wisp = { t: TUNE.wispLife, life: TUNE.wispLife, seed: G.rng() };
    emit('wisp', R.wisp);
  }
  function catchWisp() {
    const S = G.S;
    if (!R.wisp) return;
    R.wisp = null;
    S.st.wisps++;
    const e = G.WISP_EFFECTS[weighted(G.WISP_EFFECTS.map(x => x.w))];
    let amount = 0;
    if (e.id === 'frenzy' || e.id === 'storm') {
      S.buffs = S.buffs.filter(b => b.id !== e.id);
      S.buffs.push({ id: e.id, t: e.dur * D.buffDur, T: e.dur * D.buffDur });
      R.dirty = true;
    } else if (e.id === 'rain') {
      for (let i = 0; i < 8; i++) spawnChest();
    } else if (e.id === 'lucky') {
      amount = Math.min(S.gold * 0.15 + D.incomeRef * 30, D.incomeRef * 600);
      addGold(amount, 'wisp');
    } else if (e.id === 'egg') {
      addEggs(1);
    }
    questProgress('wisp', 1);
    emit('wispCatch', e, amount);
  }
  G.catchWisp = catchWisp;

  // ---------- Shop ----------
  function upgCost(u, L) { return u.base * Math.pow(u.growth, L); }
  G.upgCost = u => upgCost(u, G.S.upg[u.id] || 0);
  function buyUpgrade(id) {
    const S = G.S, u = G.UPGRADES.find(x => x.id === id);
    const L = S.upg[id] || 0;
    if (u.max && L >= u.max) return false;
    const c = upgCost(u, L);
    if (S.gold < c) return false;
    S.gold -= c; S.upg[id] = L + 1;
    R.dirty = true; recalc();
    emit('buy', 'upg', id);
    return true;
  }
  G.buyUpgrade = buyUpgrade;

  function heroCost(h, n, amount) { return G.geoCost(h.cost, G.HERO_GROWTH, n, amount); }
  G.heroCost = (h, amount) => heroCost(h, G.S.heroes[h.id] || 0, amount);
  G.heroMax = h => G.geoMax(h.cost, G.HERO_GROWTH, G.S.heroes[h.id] || 0, G.S.gold);
  function buyHero(id, amount) {
    const S = G.S, h = G.HEROES.find(x => x.id === id);
    const n = S.heroes[id] || 0;
    if (amount === 'max') amount = G.geoMax(h.cost, G.HERO_GROWTH, n, S.gold);
    if (amount <= 0) return false;
    const c = heroCost(h, n, amount);
    if (S.gold < c) return false;
    S.gold -= c; S.heroes[id] = n + amount;
    R.dirty = true; recalc();
    emit('buy', 'hero', id, amount);
    return true;
  }
  G.buyHero = buyHero;

  function nodeCost(nd, L) { return Math.ceil(nd.cost * Math.pow(nd.growth, L)); }
  G.nodeCost = nd => nodeCost(nd, G.S.nodes[nd.id] || 0);
  function nodeAvailable(nd) {
    if (!nd.req.length) return true;
    return nd.req.some(r => (G.S.nodes[r] || 0) > 0);
  }
  G.nodeAvailable = nodeAvailable;
  function buyNode(id) {
    const S = G.S, nd = G.NODE_BY_ID[id];
    const L = S.nodes[id] || 0;
    if (L >= nd.max || !nodeAvailable(nd)) return false;
    const c = nodeCost(nd, L);
    if (S.essence < c) return false;
    S.essence -= c; S.nodes[id] = L + 1;
    R.dirty = true; recalc();
    emit('buy', 'node', id);
    return true;
  }
  G.buyNode = buyNode;

  function legacyCost(l, L) { return Math.ceil(l.base * Math.pow(l.growth, L)); }
  G.legacyCost = l => legacyCost(l, G.S.legacy[l.id] || 0);
  function buyLegacy(id) {
    const S = G.S, l = G.LEGACY_BY_ID[id];
    const L = S.legacy[id] || 0;
    if (L >= l.max) return false;
    const c = legacyCost(l, L);
    if (S.fame < c) return false;
    S.fame -= c; S.legacy[id] = L + 1;
    R.dirty = true; recalc();
    emit('buy', 'legacy', id);
    return true;
  }
  G.buyLegacy = buyLegacy;

  // ---------- Pets / gacha ----------
  function pullOne() {
    const S = G.S;
    S.pity.l++; S.pity.d++; S.pulls++;
    let tier = weighted(G.PET_TIERS.map(t => t.rate));
    if (S.pity.d >= 120) tier = 3;
    else if (S.pity.l >= 25 && tier < 2) tier = 2;
    if (tier >= 2) S.pity.l = 0;
    if (tier === 3) S.pity.d = 0;
    const pet = pick(G.PETS.filter(p => p.tier === tier));
    const golden = chance(D.goldenChance);
    let st = S.pets[pet.id];
    const isNew = !st;
    const newGold = golden && (!st || !st.gold);
    if (!st) st = S.pets[pet.id] = { lvl: 1, n: 1, gold: golden };
    else { st.n++; st.lvl = Math.min(G.PET_MAX_LEVEL, st.lvl + 1); if (golden) st.gold = true; }
    return { pet, golden, isNew, newGold, lvl: st.lvl };
  }
  function pull(n) {
    const S = G.S;
    const cost = n >= 10 ? 9 : n;
    if (S.eggs < cost) return null;
    S.eggs -= cost;
    const res = [];
    for (let i = 0; i < n; i++) res.push(pullOne());
    // Auto-equip into free slots
    for (const r of res) {
      if (S.active.length < D.petSlots && !S.active.includes(r.pet.id)) S.active.push(r.pet.id);
    }
    R.dirty = true; recalc();
    emit('pull', res);
    return res;
  }
  G.pull = pull;
  function togglePet(id) {
    const S = G.S;
    if (!S.pets[id]) return;
    const i = S.active.indexOf(id);
    if (i >= 0) S.active.splice(i, 1);
    else if (S.active.length < D.petSlots) S.active.push(id);
    else { S.active.shift(); S.active.push(id); }
    R.dirty = true; recalc();
    emit('pets');
  }
  G.togglePet = togglePet;

  // ---------- Quests ----------
  function progLevel() {
    const S = G.S;
    return S.maxDepth + Math.log10(S.goldRun + 10);
  }
  const QUEST_KINDS = ['clicks', 'chests', 'rarity', 'gold', 'boss', 'crit', 'combo', 'mod', 'wisp', 'kills'];
  function makeQuest(exclude) {
    const S = G.S;
    const lv = progLevel();
    let kinds = QUEST_KINDS.filter(k => !exclude.includes(k));
    if (!S.st.bossKills && S.depth === 0) kinds = kinds.filter(k => k !== 'boss');
    if (!Object.keys(D.mods).length) kinds = kinds.filter(k => k !== 'mod');
    if (S.st.wisps < 1) kinds = kinds.filter(k => k !== 'wisp' || S.st.playTime > 240);
    const k = pick(kinds);
    const q = { k, p: 0 };
    switch (k) {
      case 'clicks': q.n = Math.round((200 + lv * 40) / 10) * 10; break;
      case 'chests': q.n = Math.round(25 + lv * 4); break;
      case 'rarity': q.r = Math.min(5, 1 + Math.floor(lv / 7)); q.n = 3; break;
      case 'gold': q.n = Math.max(200, D.incomeRef * 300); break;
      case 'boss': q.n = G.randInt(1, 3); break;
      case 'crit': q.n = Math.round((30 + lv * 5) * Math.max(0.5, D.crit / 0.05)); break;
      case 'combo': q.n = Math.min(D.comboCap, Math.round(45 + lv * 8)); break;
      case 'mod': q.n = 3; break;
      case 'wisp': q.n = 1; break;
      case 'kills': q.n = Math.round((40 + lv * 6) / 5) * 5; break;
    }
    const roll = G.rng();
    if (roll < 0.15) { q.rw = 'eggs'; q.rn = 1 + (lv > 30 ? 1 : 0); }
    else if (roll < 0.5) { q.rw = 'ess'; q.rn = Math.round(4 + lv * 1.5); }
    else { q.rw = 'gold'; q.rn = 20; } // seconds of income, paid at claim time
    return q;
  }
  function fillQuests() {
    const S = G.S;
    while (S.quests.length < 3) S.quests.push(makeQuest(S.quests.map(q => q.k)));
  }
  const QUEST_COOLDOWN = 150;
  G.fillQuests = fillQuests;
  function questProgress(kind, v, isMax) {
    const qs = G.S.quests;
    for (let i = 0; i < qs.length; i++) {
      const q = qs[i];
      if (q.done || q.wait) continue;
      if (kind === 'rarity') { if (q.k === 'rarity' && v >= q.r) q.p++; }
      else if (q.k === kind) { if (isMax) q.p = Math.max(q.p, v); else q.p += v; }
      if (q.p >= q.n) { q.p = q.n; q.done = true; emit('questDone', q); }
    }
  }
  G.questProgress = questProgress;
  function questReward(q) {
    if (q.rw === 'gold') return D.incomeRef * q.rn * D.questMult;
    if (q.rw === 'ess') return q.rn * D.questMult * D.essMult;
    return q.rn;
  }
  G.questReward = questReward;
  function claimQuest(i) {
    const S = G.S, q = S.quests[i];
    if (!q || !q.done) return false;
    const v = questReward(q);
    if (q.rw === 'gold') addGold(v, 'quest');
    else if (q.rw === 'ess') addEssence(v, 'quest');
    else addEggs(v);
    S.questsDone++;
    S.quests[i] = { wait: QUEST_COOLDOWN, k: 'wait' };
    emit('questClaim', q, v);
    return true;
  }
  G.claimQuest = claimQuest;
  function rerollQuest(i) {
    const S = G.S;
    if (Date.now() < S.rerollAt || !S.quests[i] || S.quests[i].wait) return false;
    S.quests[i] = makeQuest(S.quests.map(x => x.k));
    S.rerollAt = Date.now() + 5 * 60 * 1000;
    emit('quests');
    return true;
  }
  G.rerollQuest = rerollQuest;

  // ---------- Daily ----------
  function dailyAvailable() { return G.S.daily.last !== G.todayKey(); }
  G.dailyAvailable = dailyAvailable;
  function dailyReward(day) {
    const r = G.DAILY[day % 7];
    if (r.kind === 'gold') return { kind: 'gold', v: Math.max(500, D.incomeRef * 60 * r.mins) };
    if (r.kind === 'eggs') return { kind: 'eggs', v: r.n };
    if (r.kind === 'ess') return { kind: 'ess', v: r.n };
    return { kind: 'chest', v: 1, tier: r.tier };
  }
  G.dailyReward = dailyReward;
  function claimDaily() {
    const S = G.S;
    if (!dailyAvailable()) return null;
    const y = new Date(); y.setDate(y.getDate() - 1);
    S.daily.streak = S.daily.last === G.todayKey(y) ? S.daily.streak + 1 : 0;
    S.daily.last = G.todayKey();
    const r = dailyReward(S.daily.streak);
    if (r.kind === 'gold') addGold(r.v);
    else if (r.kind === 'eggs') addEggs(r.v);
    else if (r.kind === 'ess') addEssence(r.v);
    else openChest(makeChest(r.tier, 'ghost'), 'daily');
    emit('daily', r);
    return r;
  }
  G.claimDaily = claimDaily;

  // ---------- Ascension ----------
  // Fame depends mostly on how deep this run went (bosses gate depth), with a
  // small bonus for gold, so each ascension is worth a similar, growing amount.
  function fameGain() {
    const S = G.S, d = S.maxDepth;
    if (d < 5) return 0;
    const goldBonus = 1 + 0.1 * Math.max(0, Math.log10(Math.max(1, S.goldRun / 1e9)));
    return Math.floor(0.3 * d * Math.pow(1.07, d) * goldBonus * D.fameMult);
  }
  G.fameGain = fameGain;
  function ascend() {
    const S = G.S;
    const g = fameGain();
    if (g < 1) return false;
    const keepPct = 0.25 * (S.legacy.lg_keeppot || 0);
    const keep = {};
    G.POTIONS.forEach(p => keep[p.id] = Math.floor(S.pots[p.id] * keepPct));
    S.fame += g; S.fameTotal += g; S.ascensions++;
    S.lastRunEss = S.essRun;
    const fresh = newState();
    const runKeys = ['gold', 'goldRun', 'clicksRun', 'upg', 'heroes', 'nodes', 'essence', 'essRun', 'depth', 'maxDepth',
      'pots', 'chests', 'chestMeter', 'bossMeter', 'buffs', 'quests'];
    runKeys.forEach(k => S[k] = fresh[k]);
    S.pots = Object.assign(potZero(), keep);
    const L = S.legacy;
    if (L.lg_start) S.gold = 100 * Math.pow(10, L.lg_start);
    if (L.lg_deep) S.depth = S.maxDepth = 2 * L.lg_deep;
    if (L.lg_stars) S.essence = S.lastRunEss * 0.12 * L.lg_stars;
    R.boss = null; R.bossReady = false; R.combo = 0;
    if (G.heroReset) G.heroReset(false);
    R.dirty = true; recalc();
    fillQuests();
    emit('ascend', g);
    return g;
  }
  G.ascend = ascend;

  // ---------- Offline ----------
  function applyOffline(sec) {
    if (sec < 60) return null;
    recalc();
    const t = Math.min(sec, D.offCap);
    const gold = D.gpsBase * t * D.offEff;
    addGold(gold);
    // Scouts and the golem keep finding chests while away (opened virtually).
    const rate = D.scout + (D.autoOpen ? Math.min(1 / D.autoOpen, 2) * 0.25 : 0);
    const n = Math.min(400, Math.floor(t * rate * D.offEff));
    let items = 0, ess = 0, extraGold = 0;
    for (let i = 0; i < n; i++) {
      const l = openChest(makeChest(rollTier(), null), 'offline');
      items += l.items.length; ess += l.ess; extraGold += l.gold;
    }
    return { sec, t, gold: gold + extraGold, chests: n, items, ess };
  }
  G.applyOffline = applyOffline;

  // ---------- Main tick ----------
  function tick(dt) {
    const S = G.S;
    if (R.dirty) recalc();
    S.st.playTime += dt;

    // Buffs
    if (S.buffs.length) {
      for (const b of S.buffs) b.t -= dt;
      const before = S.buffs.length;
      S.buffs = S.buffs.filter(b => b.t > 0);
      if (S.buffs.length !== before) { R.dirty = true; recalc(); emit('buffEnd'); }
    }
    // Combo decay
    if (R.combo > 0) {
      R.comboT -= dt;
      if (R.comboT <= 0) R.combo = Math.max(0, R.combo - dt * Math.max(20, R.combo * 1.5));
    }
    // Idle income
    addGold(D.gps * dt, 'gps');
    // Auto clicks
    R.autoAcc += (D.autoCps + D.petCps) * dt;
    if (R.autoAcc >= 1) {
      const n = Math.floor(R.autoAcc);
      R.autoAcc -= n;
      autoClicks(n, dt);
    }
    // Scouts
    if (D.scout) S.chestMeter += D.scout * D.chestNeed * dt;
    spawnFromMeter();
    if (G.heroTick) G.heroTick(dt);
    // Boss
    if (R.boss) {
      const b = R.boss;
      if (R.boss) {
        b.t -= dt;
        if (b.t <= 0) bossFail();
      }
    } else if (S.bossMeter >= D.bossNeed) {
      if (!R.bossReady) { R.bossReady = true; emit('bossReady'); }
      if (D.autoBoss && S.set.autoBoss) startBoss();
    }
    // Golem auto-opener
    if (D.autoOpen) {
      R.golemAcc += dt;
      let guard = 0;
      while (R.golemAcc >= D.autoOpen && guard++ < 20) {
        R.golemAcc -= D.autoOpen;
        if (!golemAct()) { R.golemAcc = Math.min(R.golemAcc, D.autoOpen); break; }
      }
    }
    if (D.petOpen) {
      R.petOpenAcc += D.petOpen * dt;
      while (R.petOpenAcc >= 1) { R.petOpenAcc -= 1; if (!golemAct()) { R.petOpenAcc = 0; break; } }
    }
    // Chest timers
    for (let i = S.chests.length - 1; i >= 0; i--) {
      const c = S.chests[i];
      c.age += dt;
      if (c.mod === 'blazing') {
        c.life -= dt;
        if (c.life <= 0) {
          S.chests.splice(i, 1);
          const v = chestValue(c.tier) * 0.2; addGold(v);
          emit('burn', c, v);
        }
      } else if (c.mod === 'mimic') {
        if (c.awake) { c.life -= dt; if (c.life <= 0) { S.chests.splice(i, 1); emit('mimicFlee', c); } }
        else if (c.age > TUNE.mimicIdle) { S.chests.splice(i, 1); emit('mimicFlee', c); }
      }
    }
    // Wisps
    if (R.wisp) { R.wisp.t -= dt; if (R.wisp.t <= 0) { R.wisp = null; emit('wispGone'); } }
    else if (S.st.chests >= 8) {
      R.wispT -= dt * D.wispRate;
      if (R.wispT <= 0) { R.wispT = rand(TUNE.wispMin, TUNE.wispMax); spawnWisp(); }
    }
    // Quest refill timers
    for (let i = 0; i < S.quests.length; i++) {
      const q = S.quests[i];
      if (q.wait) { q.wait -= dt; if (q.wait <= 0) { S.quests[i] = makeQuest(S.quests.map(x => x.k)); emit('quests'); } }
    }
    // Periodic
    R.recalcT -= dt;
    if (R.recalcT <= 0) { R.recalcT = 0.5; recalc(); }
    R.achT -= dt;
    if (R.achT <= 0) { R.achT = 1; G.checkAchievements && G.checkAchievements(); }
  }
  G.tick = tick;

  // ---------- Save / load ----------
  function serialize() {
    const S = G.S;
    S.lastSave = Date.now();
    return JSON.stringify(S);
  }
  G.serialize = serialize;
  function deserialize(str) {
    const data = typeof str === 'string' ? JSON.parse(str) : str;
    if (!data || typeof data !== 'object' || !('gold' in data)) throw new Error('bad save');
    const fresh = newState();
    const S = Object.assign(fresh, data);
    // Merge nested objects so new fields get defaults.
    S.st = Object.assign(newState().st, data.st || {});
    S.set = Object.assign(newState().set, data.set || {});
    S.pots = Object.assign(potZero(), data.pots || {});
    S.pity = Object.assign({ l: 0, d: 0 }, data.pity || {});
    S.daily = Object.assign({ last: '', streak: 0 }, data.daily || {});
    if (!Array.isArray(S.opened) || S.opened.length !== 7) S.opened = [0, 0, 0, 0, 0, 0, 0];
    S.chests = (S.chests || []).filter(c => c && c.tier >= 0 && c.tier <= 6);
    G.S = S;
    if (G.ensureHero) G.ensureHero(S);
    if (R.mobs) R.mobs.length = 0;
    R.boss = null; R.bossReady = false; R.combo = 0; R.wisp = null;
    R.dirty = true; recalc();
    return S;
  }
  G.deserialize = deserialize;
})(globalThis.G = globalThis.G || {});

/* js/hero.js */
// BTTN — the hero: class, level, 4 gear slots, loot rolls, enchanting,
// mobs that march on the Button, combat and the power score used by the
// ladder. DOM-free like game.js, so the simulator (and later a ladder
// server) can run the exact same code.
(function (G) {
  'use strict';
  const { chance, pick, rand, randInt, emit } = G;
  const TUNE = G.TUNE;
  Object.assign(TUNE, {
    mobBase: 10, mobGrowth: 1.24, mobAtkBase: 4, mobAtkGrowth: 1.2,
    mobWalk: 9, spawnEvery: 1.3, eliteChance: 0.06,
    bossHpMobs: 25, bagMax: 30, clickVolley: 0.6, petVolley: 0.25,
    mobGold: 0.6, mobChest: 0.1, baseHp: 50,
  });

  // ---------- Content ----------
  G.SLOTS = ['weapon', 'ability', 'armor', 'ring'];
  G.RMUL = [1, 1.35, 1.8, 2.4, 3.2, 4.3, 5.8];
  // Item id -> sprite template type (weapon style, ability, armour or ring)
  G.ITEM_TYPE = {
    rusty_dagger: 'dagger', twig_staff: 'wand', short_bow: 'bow', leather_vest: 'armor', copper_ring: 'ring', old_boot: 'boot',
    steel_sword: 'sword', oak_wand: 'wand', hunter_bow: 'bow', chainmail: 'armor', emerald_ring: 'ring', hp_potion: 'potion',
    sapphire_blade: 'sword', frost_staff: 'staff', crystal_dagger: 'dagger', knight_shield: 'shield', mana_tome: 'tome', sapphire_amulet: 'amulet',
    shadow_katana: 'katana', necro_skull: 'skull', arcane_orb: 'orb', demon_helm: 'helm', void_cloak: 'cloak', amethyst_tiara: 'crown',
    dragon_sword: 'sword', phoenix_bow: 'bow', sun_staff: 'staff', golden_plate: 'armor', titan_ring: 'ring', ancient_scroll: 'scroll',
    blood_scythe: 'scythe', star_codex: 'tome', chaos_wand: 'wand', moon_orb: 'orb', realm_heart: 'heart', king_crown: 'crown',
    eternity_blade: 'sword', celestial_staff: 'staff', halo: 'halo', seraph_wing: 'wing', cosmic_egg: 'egg', golden_button: 'button',
  };
  const SLOT_OF_TYPE = {
    dagger: 'weapon', sword: 'weapon', katana: 'weapon', scythe: 'weapon', bow: 'weapon', staff: 'weapon', wand: 'weapon',
    potion: 'ability', tome: 'ability', scroll: 'ability', skull: 'ability', orb: 'ability', wing: 'ability', egg: 'ability',
    armor: 'armor', boot: 'armor', shield: 'armor', helm: 'armor', cloak: 'armor',
    ring: 'ring', amulet: 'ring', crown: 'ring', heart: 'ring', halo: 'ring', button: 'ring',
  };
  G.slotOf = id => SLOT_OF_TYPE[G.ITEM_TYPE[id]];
  // rate = attacks/s, mult = damage per attack, targets = mobs hit per attack
  G.WEAPONS = {
    dagger: { rate: 3.2, mult: 0.42, targets: 1, col: '#e6ebf2', name: { ru: 'Кинжал', en: 'Dagger' } },
    sword:  { rate: 1.6, mult: 0.85, targets: 2, col: '#ffffff', name: { ru: 'Меч', en: 'Sword' } },
    katana: { rate: 2.2, mult: 0.65, targets: 1, col: '#d4b0ff', name: { ru: 'Катана', en: 'Katana' } },
    scythe: { rate: 1.1, mult: 1.0, targets: 4, col: '#ff4f7e', name: { ru: 'Коса', en: 'Scythe' } },
    bow:    { rate: 1.3, mult: 0.95, targets: 3, col: '#9be15d', name: { ru: 'Лук', en: 'Bow' } },
    staff:  { rate: 1.4, mult: 1.0, targets: 2, col: '#5ab4ff', name: { ru: 'Посох', en: 'Staff' } },
    wand:   { rate: 2.6, mult: 0.5, targets: 1, col: '#ffe27a', name: { ru: 'Палочка', en: 'Wand' } },
  };
  const ARMOR_MUL = { armor: 1, boot: 0.7, shield: 1.2, helm: 0.9, cloak: 0.85 };
  G.ABILITIES = {
    potion: { cd: 18, name: { ru: 'Лечение', en: 'Heal' }, desc: { ru: 'Чинит кнопку на 60%', en: 'Repairs the Button by 60%' } },
    tome:   { cd: 24, name: { ru: 'Благословение', en: 'Blessing' }, desc: { ru: 'Чинит 30% и урон ×1.5 на 6 сек', en: 'Repairs 30%, damage ×1.5 for 6s' } },
    scroll: { cd: 40, name: { ru: 'Жадность', en: 'Greed' }, desc: { ru: 'Мобы роняют сундуки втрое чаще 12 сек', en: 'Mobs drop chests 3× as often for 12s' } },
    skull:  { cd: 16, name: { ru: 'Взрыв черепа', en: 'Skull Blast' }, desc: { ru: '8 ударов по всем врагам', en: 'Hits every enemy for 8 attacks' } },
    orb:    { cd: 24, name: { ru: 'Стазис', en: 'Stasis' }, desc: { ru: 'Замедляет мобов, урон +30% на 6 сек', en: 'Slows mobs, +30% damage for 6s' } },
    wing:   { cd: 30, name: { ru: 'Крылья', en: 'Wings' }, desc: { ru: 'Скорость атаки ×2 на 8 сек', en: 'Attack speed ×2 for 8s' } },
    egg:    { cd: 30, name: { ru: 'Звездопад', en: 'Starfall' }, desc: { ru: '15 ударов по цели и 4 по всем', en: '15 hits on the target, 4 on everyone' } },
  };
  G.CLASSES = [
    { id: 'knight', spr: 'h_knight', weapons: ['sword', 'katana', 'scythe'], starter: 'steel_sword', hp: 1.3, crit: 0, extra: 0,
      name: { ru: 'Рыцарь', en: 'Knight' }, desc: { ru: 'Мечи, катаны и косы. Кнопка крепче на 30%.', en: 'Swords, katanas and scythes. The Button is 30% tougher.' } },
    { id: 'archer', spr: 'h_archer', weapons: ['bow'], starter: 'short_bow', hp: 1, crit: 0, extra: 1,
      name: { ru: 'Лучник', en: 'Archer' }, desc: { ru: 'Луки. Стрелы пробивают ещё одного врага.', en: 'Bows. Arrows pierce one more enemy.' } },
    { id: 'wizard', spr: 'h_wizard', weapons: ['staff', 'wand'], starter: 'twig_staff', hp: 1, crit: 0, extra: 0, spd: 0.15,
      name: { ru: 'Маг', en: 'Wizard' }, desc: { ru: 'Посохи и палочки. Атакует на 15% быстрее.', en: 'Staves and wands. Attacks 15% faster.' } },
    { id: 'rogue', spr: 'h_rogue', weapons: ['dagger'], starter: 'rusty_dagger', hp: 1, crit: 0.1, extra: 0,
      name: { ru: 'Разбойник', en: 'Rogue' }, desc: { ru: 'Кинжалы. +10% шанс крита.', en: 'Daggers. +10% crit chance.' } },
  ];
  G.CLASS_BY_ID = {}; G.CLASSES.forEach(c => G.CLASS_BY_ID[c.id] = c);
  G.AFFIXES = {
    dmg:   { v: [0.04, 0.10], name: { ru: 'Урон', en: 'Damage' } },
    spd:   { v: [0.03, 0.08], name: { ru: 'Скорость атаки', en: 'Attack speed' } },
    crit:  { v: [0.01, 0.03], name: { ru: 'Шанс крита', en: 'Crit chance' } },
    critd: { v: [0.10, 0.30], name: { ru: 'Сила крита', en: 'Crit power' }, x: true },
    hp:    { v: [0.05, 0.12], name: { ru: 'Прочность кнопки', en: 'Button toughness' } },
    gold:  { v: [0.04, 0.12], name: { ru: 'Золото', en: 'Gold' } },
    luck:  { v: [0.02, 0.06], name: { ru: 'Удача', en: 'Luck' } },
    xp:    { v: [0.05, 0.15], name: { ru: 'Опыт', en: 'Experience' } },
    shard: { v: [0.05, 0.15], name: { ru: 'Осколки', en: 'Shards' } },
  };
  const AFFIX_COUNT = [0, 1, 1, 2, 2, 3, 3];
  const SALVAGE = [1, 2, 4, 8, 16, 32, 64];
  G.ENCHANT_MAX = 20;

  // ---------- State ----------
  function newHero() {
    return { cls: null, lvl: 1, xp: 0, eq: { weapon: null, ability: null, armor: null, ring: null }, bag: [], gu: 0,
      shards: 0, hp: TUNE.baseHp, auto: 1, salv: 1, cast: 1, kills: 0, elites: 0, fresh: 0 };
  }
  G.newHero = newHero;
  function ensureHero(S) {
    S.hero = Object.assign(newHero(), S.hero || {});
    S.hero.eq = Object.assign({ weapon: null, ability: null, armor: null, ring: null }, S.hero.eq || {});
    if (!Array.isArray(S.hero.bag)) S.hero.bag = [];
    if (!S.profile) S.profile = { id: Math.random().toString(36).slice(2, 10), name: '' };
    S.rec = Object.assign({ maxPower: 0, maxLevel: 1, madTime: 0, runStart: Date.now() }, S.rec || {});
  }
  G.ensureHero = ensureHero;

  const R = G.R;
  ensureHero(G.S);
  Object.assign(R, { mobs: [], mobUid: 0, spawnT: 2, heroAcc: 0, abilCd: 0, hb: {}, stun: 0, bossAtkT: 2 });

  // ---------- Gear ----------
  function rollAffixes(r) {
    const keys = Object.keys(G.AFFIXES), out = [];
    const n = AFFIX_COUNT[r];
    while (out.length < n) {
      const k = pick(keys);
      if (out.some(a => a[0] === k)) continue;
      const v = G.AFFIXES[k].v;
      out.push([k, +(G.lerp(v[0], v[1], G.rng()) * (1 + 0.35 * r)).toFixed(4)]);
    }
    return out;
  }
  function makeGear(id, il) {
    const it = G.ITEM_BY_ID[id], h = G.S.hero;
    return { u: ++h.gu, id, r: it.r, il: Math.max(0, il | 0), e: 0, a: rollAffixes(it.r) };
  }
  G.makeGear = makeGear;
  const enchantMul = g => 1 + 0.12 * g.e;
  // The item's main stat: damage per hit, button HP, or % bonus
  function mainStat(g) {
    const type = G.ITEM_TYPE[g.id], slot = SLOT_OF_TYPE[type];
    const scale = G.RMUL[g.r] * Math.pow(1.16, g.il) * enchantMul(g);
    if (slot === 'weapon') return 8 * scale;
    if (slot === 'armor') return 60 * scale * ARMOR_MUL[type];
    if (slot === 'ring') return 0.04 * G.RMUL[g.r] * enchantMul(g) * (1 + g.il * 0.02);
    return 0.02 * G.RMUL[g.r] * enchantMul(g) * (1 + g.il * 0.02);
  }
  G.mainStat = mainStat;

  // Full combat numbers for a given set of equipped items
  function combat(eq, d, who) {
    const h = who || G.S.hero;
    const cls = G.CLASS_BY_ID[h.cls] || G.CLASSES[0];
    const aff = {};
    for (const slot of G.SLOTS) {
      const g = eq[slot];
      if (g) for (const [k, v] of g.a) aff[k] = (aff[k] || 0) + v;
    }
    const w = eq.weapon;
    const wtype = w ? G.ITEM_TYPE[w.id] : 'dagger';
    const wt = G.WEAPONS[wtype];
    const lvlM = 1 + 0.05 * (h.lvl - 1);
    const own = cls.weapons.includes(wtype) ? 1.5 : 1;
    const pct = 1 + (aff.dmg || 0) + (eq.ring ? mainStat(eq.ring) : 0) + (eq.ability ? mainStat(eq.ability) : 0);
    const base = (w ? mainStat(w) : 4) * own * lvlM * pct * (d.heroMult || 1);
    const hit = base * wt.mult;
    const rate = wt.rate * (1 + (aff.spd || 0) + (cls.spd || 0)) * (d.spdMult || 1);
    const crit = Math.min(0.9, (d.crit || 0.03) + (aff.crit || 0) + cls.crit);
    const critMult = (d.critMult || 3) + (aff.critd || 0);
    const targets = wt.targets + cls.extra;
    const hp = (eq.armor ? mainStat(eq.armor) : TUNE.baseHp) * lvlM * cls.hp * (1 + (aff.hp || 0)) * (d.hpMult || 1);
    const dps = hit * rate * (1 + crit * (critMult - 1));
    const power = Math.floor(dps * (1 + 0.15 * (targets - 1)) * Math.sqrt(hp / TUNE.baseHp) * 10);
    return { aff, wtype, wt, hit, rate, crit, critMult, targets, hp, dps, power, own: own > 1 };
  }
  G.heroCombat = combat;

  function powerWith(slot, g) {
    const eq = Object.assign({}, G.S.hero.eq);
    eq[slot] = g;
    return combat(eq, G.D).power;
  }
  G.powerWith = powerWith;

  function gainGear(it, srcTier) {
    const S = G.S, h = S.hero;
    if (!h) return null;
    const g = makeGear(it.id, S.depth + (chance(0.35) ? 1 : 0));
    h.fresh++;
    const slot = G.slotOf(g.id);
    let equipped = false;
    if (h.auto && h.cls) {
      const cur = h.eq[slot];
      if (!cur || powerWith(slot, g) > powerWith(slot, cur)) { equip(g, true); equipped = true; }
    }
    if (!equipped) {
      if (h.salv && g.r < h.salv) { salvage(g, true); return g; }
      h.bag.push(g);
    }
    while (h.bag.length > TUNE.bagMax) {
      {
        // Drop the weakest item in the bag into shards
        let worst = null, ws = Infinity;
        for (const b of h.bag) { const s = powerWith(G.slotOf(b.id), b); if (s < ws) { ws = s; worst = b; } }
        salvage(worst, true);
      }
    }
    emit('gear', g, equipped);
    return g;
  }
  G.gainGear = gainGear;

  function equip(g, silent) {
    const h = G.S.hero, slot = G.slotOf(g.id);
    const old = h.eq[slot];
    const i = h.bag.indexOf(g);
    if (i >= 0) h.bag.splice(i, 1);
    h.eq[slot] = g;
    if (old) h.bag.push(old);
    G.dirty(); G.recalc();
    if (!silent) emit('equip', g);
    return true;
  }
  G.equip = equip;
  function unequip(slot) {
    const h = G.S.hero, g = h.eq[slot];
    if (!g) return false;
    h.eq[slot] = null; h.bag.push(g);
    G.dirty(); G.recalc(); emit('equip', null);
    return true;
  }
  G.unequip = unequip;

  function salvageValue(g) { return Math.ceil(SALVAGE[g.r] * (1 + g.il * 0.05) * (1 + 0.5 * g.e) * (G.D.shardMult || 1)); }
  G.salvageValue = salvageValue;
  function salvage(g, silent) {
    const h = G.S.hero;
    const i = h.bag.indexOf(g);
    if (i >= 0) h.bag.splice(i, 1);
    for (const s of G.SLOTS) if (h.eq[s] === g) return 0; // never scrap what you wear
    const v = salvageValue(g);
    h.shards += v;
    if (!silent) emit('salvage', g, v);
    return v;
  }
  G.salvage = salvage;
  G.salvageBelow = function (r) {
    const h = G.S.hero;
    let n = 0, v = 0;
    for (const g of h.bag.slice()) if (g.r < r) { v += salvage(g, true); n++; }
    emit('salvage', null, v);
    return { n, v };
  };

  function enchantCost(g) {
    return { shards: Math.ceil(4 * Math.pow(1.5, g.e) * G.RMUL[g.r]), gold: Math.max(50, G.D.incomeRef * 6 * Math.pow(1.3, g.e)) };
  }
  G.enchantCost = enchantCost;
  function enchant(g) {
    const S = G.S, h = S.hero;
    if (g.e >= G.ENCHANT_MAX) return false;
    const c = enchantCost(g);
    if (h.shards < c.shards || S.gold < c.gold) return false;
    h.shards -= c.shards; S.gold -= c.gold; g.e++;
    G.dirty(); G.recalc();
    emit('enchant', g);
    return true;
  }
  G.enchant = enchant;

  function chooseClass(id) {
    const S = G.S, h = S.hero, cls = G.CLASS_BY_ID[id];
    if (!cls) return false;
    h.cls = id;
    const hasWeapon = [h.eq.weapon].concat(h.bag).some(g => g && G.slotOf(g.id) === 'weapon' && cls.weapons.includes(G.ITEM_TYPE[g.id]));
    if (!hasWeapon) { const g = makeGear(cls.starter, 0); h.bag.push(g); }
    // Wear the best weapon for the new class
    let best = h.eq.weapon, bp = best ? powerWith('weapon', best) : -1;
    for (const g of h.bag) if (G.slotOf(g.id) === 'weapon') { const p = powerWith('weapon', g); if (p > bp) { bp = p; best = g; } }
    if (best && best !== h.eq.weapon) equip(best, true);
    G.dirty(); G.recalc();
    h.hp = G.D.heroHp;
    emit('classChosen', cls);
    return true;
  }
  G.chooseClass = chooseClass;

  // ---------- Hooks called from recalc ----------
  // Economy side of gear affixes, applied before gold multipliers are summed
  G.heroEcon = function (d) {
    const h = G.S.hero;
    if (!h) return;
    const aff = {};
    for (const slot of G.SLOTS) { const g = h.eq[slot]; if (g) for (const [k, v] of g.a) aff[k] = (aff[k] || 0) + v; }
    d.goldMult *= 1 + (aff.gold || 0);
    d.luck += aff.luck || 0;
    d.xpMult = 1 + (aff.xp || 0);
    d.shardMult = 1 + (aff.shard || 0);
  };
  G.heroFinish = function (d) {
    const S = G.S, h = S.hero;
    if (!h) return;
    d.heroMult = (d.heroMult || 1) * (1 + 0.005 * S.fameTotal) * (1 + 0.02 * (d.heroClasses || 0));
    const c = combat(h.eq, d);
    const buffDmg = (R.hb.tome > 0 ? 1.5 : 1) * (R.hb.orb > 0 ? 1.3 : 1);
    d.hero = c;
    d.heroHit = c.hit * buffDmg;
    d.heroRate = c.rate * (R.hb.wing > 0 ? 2 : 1);
    d.heroHp = c.hp;
    d.heroDps = c.dps * buffDmg;
    d.power = c.power;
    if (h.hp > c.hp) h.hp = c.hp;
    if (c.power > S.rec.maxPower) S.rec.maxPower = c.power;
  };

  // ---------- Mobs & combat ----------
  function mobHp(d) { return TUNE.mobBase * Math.pow(TUNE.mobGrowth, d); }
  function mobAtk(d) { return TUNE.mobAtkBase * Math.pow(TUNE.mobAtkGrowth, d); }
  G.mobHp = mobHp; G.mobAtk = mobAtk;
  G.bossHp = d => mobHp(d) * TUNE.bossHpMobs * (G.isLord(d) ? TUNE.lordHp : 1);
  const maxAlive = d => 6 + Math.min(6, Math.floor(d / 5));
  function xpNeed(l) { return Math.floor(15 * Math.pow(1.2, l - 1) + 10 * l); }
  G.xpNeed = xpNeed;

  function spawnMob() {
    const S = G.S;
    const elite = chance(TUNE.eliteChance);
    const hp = mobHp(S.depth) * (elite ? 4 : 1);
    const m = { id: ++R.mobUid, hp, max: hp, p: 0, sp: 1 / (TUNE.mobWalk * rand(0.85, 1.15)), atkT: 0, elite, a: G.rng() };
    R.mobs.push(m);
    emit('mobSpawn', m);
  }
  function targets(n) {
    if (R.boss) return [];
    const list = R.mobs.slice().sort((a, b) => b.p - a.p);
    const fi = R.focus ? list.findIndex(m => m.id === R.focus) : -1;
    if (fi > 0) list.unshift(list.splice(fi, 1)[0]);
    else if (fi < 0) R.focus = null;
    return list.slice(0, n);
  }
  function dealHit(m, dmg) {
    m.hp -= dmg;
    if (m.hp <= 0 && !m.dead) killMob(m);
  }
  function killMob(m) {
    const S = G.S, D = G.D, h = S.hero;
    m.dead = true;
    R.mobs.splice(R.mobs.indexOf(m), 1);
    const k = m.elite ? 3 : 1;
    const gold = D.incomeRef * TUNE.mobGold * k;
    G.addGold(gold, 'mob');
    gainXp((1 + S.depth) * k * (D.xpMult || 1));
    h.kills++; if (m.elite) h.elites++;
    S.bossMeter++;
    let chest = null;
    const p = m.elite ? 1 : TUNE.mobChest * (R.hb.scroll > 0 ? 3 : 1);
    if (chance(p)) chest = G.spawnChest();
    G.questProgress('kills', 1);
    emit('mobDie', m, gold, chest);
  }
  function gainXp(x) {
    const S = G.S, h = S.hero;
    h.xp += x;
    let up = false;
    while (h.xp >= xpNeed(h.lvl)) { h.xp -= xpNeed(h.lvl); h.lvl++; up = true; }
    if (up) {
      if (h.lvl > S.rec.maxLevel) S.rec.maxLevel = h.lvl;
      G.dirty(); G.recalc();
      h.hp = G.D.heroHp;
      emit('levelUp', h.lvl);
    }
  }
  G.gainXp = gainXp;

  // One attack of the hero's weapon (k scales it: clicks and pets fire partial volleys)
  function attack(k, src) {
    const D = G.D;
    if (!G.S.hero.cls) return;
    const crit = chance(D.hero.crit);
    const dmg = D.heroHit * k * (crit ? D.hero.critMult : 1);
    if (R.boss) {
      G.hitBoss(dmg * D.bossMult);
      emit('heroAttack', { boss: true, crit, src, dmg });
      return;
    }
    const ts = targets(D.hero.targets);
    if (!ts.length) return;
    emit('heroAttack', { ids: ts.map(m => m.id), crit, src, dmg });
    for (const m of ts) dealHit(m, dmg);
  }
  G.heroVolley = attack;

  function hurtButton(dmg) {
    const h = G.S.hero;
    if (R.stun > 0) return;
    h.hp -= dmg;
    emit('buttonHurt', dmg);
    if (h.hp <= 0) breakButton();
  }
  function breakButton() {
    const S = G.S, h = S.hero;
    R.stun = 4;
    h.hp = G.D.heroHp;
    for (const m of R.mobs) emit('mobFlee', m);
    R.mobs.length = 0;
    S.bossMeter = Math.floor(S.bossMeter * 0.5);
    if (R.boss) G.fleeBoss();
    emit('buttonBreak');
  }

  function castAbility() {
    const S = G.S, D = G.D, h = S.hero;
    const g = h.eq.ability;
    if (!g || R.abilCd > 0 || !h.cls) return false;
    const type = G.ITEM_TYPE[g.id], ab = G.ABILITIES[type];
    R.abilCd = ab.cd * (1 - Math.min(0.5, 0.03 * g.e));
    const hit = D.heroHit;
    switch (type) {
      case 'potion': h.hp = Math.min(D.heroHp, h.hp + D.heroHp * 0.6); break;
      case 'tome': h.hp = Math.min(D.heroHp, h.hp + D.heroHp * 0.3); R.hb.tome = 6; break;
      case 'scroll': R.hb.scroll = 12; break;
      case 'orb': R.hb.orb = 6; break;
      case 'wing': R.hb.wing = 8; break;
      case 'skull':
        if (R.boss) G.hitBoss(hit * 8 * D.bossMult);
        for (const m of R.mobs.slice()) dealHit(m, hit * 8);
        break;
      case 'egg':
        if (R.boss) G.hitBoss(hit * 15 * D.bossMult);
        else { const t = targets(1)[0]; if (t) dealHit(t, hit * 11); }
        for (const m of R.mobs.slice()) dealHit(m, hit * 4);
        break;
    }
    G.dirty(); G.recalc();
    emit('ability', type);
    return true;
  }
  G.castAbility = castAbility;

  G.heroTick = function (dt) {
    const S = G.S, D = G.D, h = S.hero;
    if (!h || !h.cls) return;
    // ability buffs
    let changed = false;
    for (const k in R.hb) { if (R.hb[k] > 0) { R.hb[k] -= dt; if (R.hb[k] <= 0) changed = true; } }
    if (changed) { G.dirty(); G.recalc(); }
    if (R.abilCd > 0) R.abilCd -= dt;
    if (R.stun > 0) R.stun -= dt;
    // regen
    h.hp = Math.min(D.heroHp, h.hp + D.heroHp * 0.03 * dt);
    // spawn
    if (!R.boss && R.stun <= 0 && R.mobs.length < maxAlive(S.depth)) {
      R.spawnT -= dt;
      if (R.spawnT <= 0) { R.spawnT = TUNE.spawnEvery * rand(0.7, 1.3); spawnMob(); }
    }
    // walk & bite
    const slow = R.hb.orb > 0 ? 0.4 : 1;
    const atk = mobAtk(S.depth);
    for (const m of R.mobs.slice()) {
      if (m.p < 1) m.p = Math.min(1, m.p + m.sp * dt * slow);
      else { m.atkT -= dt; if (m.atkT <= 0) { m.atkT = 1; hurtButton(atk * (m.elite ? 2 : 1)); emit('mobBite', m); } }
    }
    // boss hits the button too
    if (R.boss) {
      R.bossAtkT -= dt;
      if (R.bossAtkT <= 0) { R.bossAtkT = 2; hurtButton(atk * (R.boss.lord ? 5 : 3)); }
    }
    // hero attacks
    R.heroAcc += dt * D.heroRate;
    let guard = 0;
    while (R.heroAcc >= 1 && guard++ < 30) { R.heroAcc -= 1; attack(1, 'auto'); }
    if (R.heroAcc > 5) R.heroAcc = 0;
    // autocast
    if (h.cast && R.abilCd <= 0 && h.eq.ability) {
      const type = G.ITEM_TYPE[h.eq.ability.id];
      const want = type === 'potion' ? h.hp < D.heroHp * 0.5
        : type === 'tome' ? (h.hp < D.heroHp * 0.7 || R.boss)
        : R.boss || R.mobs.length >= 3;
      if (want) castAbility();
    }
  };

  G.heroBossStart = function () {
    for (const m of R.mobs) emit('mobFlee', m);
    R.mobs.length = 0;
    R.bossAtkT = 2;
  };
  G.heroReset = function (keepClass) {
    const h = G.S.hero;
    h.lvl = 1; h.xp = 0;
    if (!keepClass) h.cls = null;
    R.mobs.length = 0; R.hb = {}; R.abilCd = 0; R.stun = 0;
    G.S.rec.runStart = Date.now();
    G.dirty(); G.recalc();
    h.hp = G.D.heroHp || TUNE.baseHp;
  };

  // ---------- Ladder snapshot ----------
  // A compact, canonical description of the character. A future ladder server
  // recomputes power from this with the same combat() code, so a client
  // can't just send a big number.
  G.ladderSnapshot = function () {
    const S = G.S, h = S.hero;
    const gear = {};
    for (const s of G.SLOTS) { const g = h.eq[s]; gear[s] = g ? { id: g.id, r: g.r, il: g.il, e: g.e, a: g.a } : null; }
    const snap = {
      v: 1, name: (S.profile.name || '').slice(0, 16), cls: h.cls, lvl: h.lvl,
      depth: S.bestDepth, asc: S.ascensions, fame: S.fameTotal, mad: Math.round(S.rec.madTime || 0), gear, ts: Date.now(),
    };
    snap.power = G.ladderPower(snap);
    return snap;
  };

  // Ladder power: gear, level and class only, with neutral global bonuses,
  // so every client and the server compute the same number from a snapshot.
  const NEUTRAL = { crit: 0.03, critMult: 3, spdMult: 1, heroMult: 1, hpMult: 1 };
  G.ladderPower = function (snap) {
    const eq = {};
    for (const s of G.SLOTS) eq[s] = snap.gear && snap.gear[s] ? snap.gear[s] : null;
    return combat(eq, NEUTRAL, { cls: snap.cls, lvl: snap.lvl }).power;
  };

  // Plausibility check for a snapshot from someone else's client (or a
  // server request). Returns the list of problems; empty means it passes.
  G.verifySnapshot = function (snap) {
    const bad = [];
    const int = (v, lo, hi) => Number.isInteger(v) && v >= lo && v <= hi;
    if (!snap || typeof snap !== 'object') return ['shape'];
    if (!G.CLASS_BY_ID[snap.cls]) bad.push('class');
    if (!int(snap.depth, 0, 100000)) bad.push('depth');
    if (!int(snap.lvl, 1, 30 + 2 * (snap.depth | 0))) bad.push('level');
    if (typeof snap.name !== 'string' || snap.name.length > 16) bad.push('name');
    const gear = snap.gear || {};
    for (const s of G.SLOTS) {
      const g = gear[s];
      if (g == null) continue;
      const it = G.ITEM_BY_ID[g.id];
      if (!it || G.slotOf(g.id) !== s || g.r !== it.r) { bad.push(s + ':item'); continue; }
      if (!int(g.il, 0, (snap.depth | 0) + 3)) bad.push(s + ':ilvl');
      if (!int(g.e, 0, G.ENCHANT_MAX)) bad.push(s + ':enchant');
      if (!Array.isArray(g.a) || g.a.length > AFFIX_COUNT[g.r]) { bad.push(s + ':affixes'); continue; }
      const seen = {};
      for (const a of g.a) {
        const def = Array.isArray(a) && G.AFFIXES[a[0]];
        if (!def || seen[a[0]] || typeof a[1] !== 'number') { bad.push(s + ':affix'); break; }
        seen[a[0]] = 1;
        const k = 1 + 0.35 * g.r;
        if (a[1] < def.v[0] * k - 1e-3 || a[1] > def.v[1] * k + 1e-3) { bad.push(s + ':range'); break; }
      }
    }
    if (typeof snap.power === 'number' && !bad.length && G.ladderPower(snap) !== snap.power) bad.push('power');
    return bad;
  };
})(globalThis.G = globalThis.G || {});
