// BTTN ladder server — Cloudflare Worker + D1.
// Runs the same game logic as the client (src/game.js is generated by
// tools/build.js from js/util.js, data.js, game.js, hero.js), so ladder
// power is recomputed here from the gear snapshot instead of trusted.
import './game.js';

const G = globalThis.G;
const MAX_SAVE = 400 * 1024;
const LADDER_COOLDOWN = 10e3;

const json = (env, body, status = 200) => new Response(JSON.stringify(body), {
  status,
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'access-control-allow-origin': env.ALLOW_ORIGIN || '*',
    'access-control-allow-headers': 'content-type, authorization',
    'access-control-allow-methods': 'GET, POST, PUT, OPTIONS',
  },
});

// token = <id>.<base64url(HMAC-SHA256(secret, id))>
async function sign(env, id) {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(env.SECRET || 'dev-secret'),
    { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const mac = new Uint8Array(await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(id)));
  let s = ''; for (const b of mac) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
async function playerFrom(req, env) {
  const h = req.headers.get('authorization') || '';
  const token = h.startsWith('Bearer ') ? h.slice(7) : '';
  const [id, mac] = token.split('.');
  if (!id || !mac || mac !== await sign(env, id)) return null;
  return await env.DB.prepare('SELECT id, flagged FROM players WHERE id = ?').bind(id).first();
}

async function readJson(req, limit) {
  const text = await req.text();
  if (text.length > limit) throw Object.assign(new Error('too_large'), { status: 413 });
  try { return JSON.parse(text); } catch (e) { throw Object.assign(new Error('bad_json'), { status: 400 }); }
}

export default {
  async fetch(req, env) {
    if (req.method === 'OPTIONS') return json(env, {});
    const url = new URL(req.url);
    const route = req.method + ' ' + url.pathname;
    const season = +(env.SEASON || 1);
    try {
      if (route === 'POST /api/auth') {
        const id = crypto.randomUUID();
        await env.DB.prepare('INSERT INTO players (id, created_at) VALUES (?, ?)').bind(id, Date.now()).run();
        return json(env, { id, token: id + '.' + await sign(env, id) });
      }
      if (route === 'GET /api/ladder') {
        const by = url.searchParams.get('by') === 'power' ? 'power DESC' : 'depth DESC, power DESC';
        const limit = Math.max(1, Math.min(300, +url.searchParams.get('limit') || 100));
        const rows = await env.DB.prepare(`SELECT player_id, snapshot FROM ladder WHERE season = ? ORDER BY ${by} LIMIT ?`).bind(season, limit).all();
        const entries = (rows.results || []).map(r => Object.assign(JSON.parse(r.snapshot), { uid: r.player_id }));
        return json(env, { season, entries });
      }

      const me = await playerFrom(req, env);
      if (!me) return json(env, { error: 'unauthorized' }, 401);

      if (route === 'GET /api/me') return json(env, { id: me.id, flagged: !!me.flagged });

      if (route === 'GET /api/save') {
        const row = await env.DB.prepare('SELECT data, ts FROM saves WHERE player_id = ?').bind(me.id).first();
        return json(env, { save: row ? { data: row.data, ts: row.ts } : null });
      }
      if (route === 'PUT /api/save') {
        const body = await readJson(req, MAX_SAVE + 1024);
        if (typeof body.data !== 'string' || body.data.length > MAX_SAVE) return json(env, { error: 'bad_save' }, 400);
        let parsed;
        try { parsed = JSON.parse(body.data); } catch (e) { return json(env, { error: 'bad_save' }, 400); }
        if (!parsed || typeof parsed.gold !== 'number') return json(env, { error: 'bad_save' }, 400);
        await env.DB.prepare('INSERT INTO saves (player_id, data, ts, updated_at) VALUES (?, ?, ?, ?) ' +
          'ON CONFLICT(player_id) DO UPDATE SET data = excluded.data, ts = excluded.ts, updated_at = excluded.updated_at')
          .bind(me.id, body.data, +body.ts || Date.now(), Date.now()).run();
        return json(env, { ok: true });
      }
      if (route === 'PUT /api/ladder') {
        if (me.flagged) return json(env, { error: 'flagged' }, 403);
        const snap = await readJson(req, 16 * 1024);
        const problems = G.verifySnapshot(snap);
        if (problems.length) return json(env, { error: 'rejected', problems }, 422);
        const prev = await env.DB.prepare('SELECT updated_at FROM ladder WHERE player_id = ?').bind(me.id).first();
        if (prev && Date.now() - prev.updated_at < LADDER_COOLDOWN) return json(env, { error: 'too_soon' }, 429);
        const clean = {
          v: 1, name: String(snap.name || '').slice(0, 16), cls: snap.cls, lvl: snap.lvl, depth: snap.depth,
          asc: snap.asc | 0, fame: +snap.fame || 0, mad: snap.mad | 0, gear: snap.gear, ts: Date.now(),
          rift: snap.rift | 0, rt: snap.rt | 0, rd: snap.rd || null, uq: snap.uq | 0, kills: snap.kills | 0, ls: snap.ls | 0, ev: Array.isArray(snap.ev) ? snap.ev : [], fs: snap.fs || {}, cr: snap.cr || {},
        };
        clean.power = G.ladderPower(clean); // never trust the client's number
        await env.DB.prepare('INSERT INTO ladder (player_id, season, name, cls, lvl, depth, power, snapshot, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ' +
          'ON CONFLICT(player_id) DO UPDATE SET season = excluded.season, name = excluded.name, cls = excluded.cls, lvl = excluded.lvl, ' +
          'depth = excluded.depth, power = excluded.power, snapshot = excluded.snapshot, updated_at = excluded.updated_at')
          .bind(me.id, season, clean.name, clean.cls, clean.lvl, clean.depth, clean.power, JSON.stringify(clean), Date.now()).run();
        return json(env, { ok: true, power: clean.power });
      }
      return json(env, { error: 'not_found' }, 404);
    } catch (e) {
      return json(env, { error: e.message || 'server_error' }, e.status || 500);
    }
  },
};
